### ISSUE TITLE
Filesize.

### ISSUE THREAD

**Issue by Boycce** [braintree/braintree-web#122]
Hey there, thanks for your work, but am quite concerned how large this library is.

V2 is **132kb** bigger than V1, totalling around 174kb. Is there any way to modularise this so we can choose what to include in our bundles? Cheers.

**Comment by EvanHahn** [comment]
v2 is a much bigger library than v1 because it's a pretty different library with many more features. We want to make the file size smaller but haven't found a backwards-compatible way to do it.

This is something that we're looking into for the next major version, but we can't give a hard date or make any promises. We'll update this thread when there's more to tell!

**Comment by Boycce** [comment]
Hey cheers @EvanHahn for the status. Yeah it would go long way, even if it means providing a non-backwards compatible source.

**Comment by mrak** [comment]
We've released a beta of our next major version. Here are some links to our official documentation:

[Setup for v3](https://developers.braintreepayments.com/guides/client-sdk/setup/javascript/v3)
[Migrating from v2 to v3](https://developers.braintreepayments.com/guides/client-sdk/migration/javascript/v3)
