### ISSUE TITLE
onReady not firing?

### ISSUE THREAD

**Issue by dougjohnston** [braintree/braintree-web#129]
We're using Hosted Forms and I'm seeing an issue for ~5% of our users where the payment form does not seem to load.

I am hiding the form via CSS while it is loading and then, when the onReady event fires, the form is displayed. This works fine for the majority of our users, but for about 5%, the onReady event does not seem to fire.

Here's part of the view code:

```ruby
<%= javascript_include_tag "https://js.braintreegateway.com/js/braintree-2.19.0.min.js" %>
<script>
  braintree.setup("<%= Braintree::ClientToken.generate %>", "custom", {
    id: "braintree-form",
    onReady: function(event) {
      RS.braintree.displayForm();
    },
   ...
```

The call to `RS.braintree.displayForm()` points here:

```javascript
displayForm: function() {
  this.formLoaded = true;
  $('#payment-wrapper').fadeIn('fast');
  $('#payment-loading').hide();
},
```
A little more info:
On `document.ready`, I set an interval which checks every 1/2 second to see if `this.formLoaded` has been set to `true`. If after 50 seconds, it has not been set, it notifies me and the customer that the payment form could not be loaded and that they should try refreshing the page.

On occasion, they will refresh the page and it works. They'll be able to see the form and submit a payment. More often, I can see in the logs that they refresh the page multiple times without success. The 5% of users this affects is all over the place when it comes to browser, OS, and geographic location.

I'm at a bit of a loss as to what could be causing this. Is it an issue with my code?

**Comment by mrak** [comment]
Thanks for the detailed information up front!

Have you seen anything coming from the `onError` callback?

I know you're familiar with our reference, but I'll link here for convenience:

[JavaScript v2 Reference - Setup method options](https://developers.braintreepayments.com/reference/client-reference/javascript-v2-reference#setup-method-options)

**Comment by dougjohnston** [comment]
I don't believe so. I'm triggering an AJAX notification whenever onError is triggered or if the form doesn't load. For these issues, I'm only seeing notifications that the form didn't load, so I don't think onError is being triggered.

I have been able to reproduce the issue by artificially limiting my bandwidth down to 50 kbps. I think networking *could* be one of the causes and I'm going to be putting braintree.js into our Rails asset pipeline to see if that makes a difference. I don't *think* all these issues are coming from people on dial-up or really crappy connections, but it's possible.

**Comment by dougjohnston** [comment]
Also, case #623516 has been opened for this issue.

**Comment by mrak** [comment]
@dougjohnston great! 

I'll follow up with our support team through that issue.

**Comment by mrak** [comment]
Closing as this issue has been taken out-of-band

**Comment by beaurepair** [comment]
Have found that the following css is preventing the onready and onerror events from firing.

`iframe{
	height: auto;
}`

**Comment by rickhall** [comment]
Why close this when taken out of band? I'm still interested in reading about the conclusion, since I am experiencing a similar issue.

**Comment by dougjohnston** [comment]
The issue was related to Kaspersky's SecureMoney product. They apparently released an update some months back which broke Braintree forms. The forms would not load, no matter how many times the user refreshed. The only solution (for a while) was to get the user to temporarily disable Kaspersky. We updated our error message to reflect this, but some customers understandably didn't feel comfortable disabling Kaspersky.

About a month ago, Kaspersky fixed the issue. It has taken time to roll out to customers, especially those who don't have auto-update turned on, but we have noticed a decrease in frequency. It still does happen occasionally, which may point to other issues at play. But, since we've seen the number of issues drop from ~5% of customers to > 1%, we haven't put much more time into it. If, in a couple months, we are still noticing this issue, we may take another look.

**Comment by rickhall** [comment]
I am seeing the issue in my single page web app, where I tear down and recreate braintree. In cases where I do this quickly, I see times when onReady() doesn't fire. I was hiding my UI too, but after reading this I tried the same experiment without hiding it and still could make the issue arise. Not sure what to do. Like you suggest, it doesn't look like it would happen a lot, but it bothers me that it can happen at all.

**Comment by lilaconlee** [comment]
@rickhall It sounds like your difficulties with `onReady` are different than the ones described in this issue. We'd love to help you out if you would open a new issue and include some more information about your integration, such as what version of `braintree.js` you are using as well as what browsers you've seen this in.

**Comment by rickhall** [comment]
Thanks, I think I've narrowed it down. It might be related to my specific approach in my single page web app. Using braintree in such a context is tricky. Braintree doesn't like the form messed with after the fact or else it won't be able to teardown correctly and/or may not become ready subsequently.

Given the component-oriented approach of my system, I had to account for the fact that the component displaying the braintree hosted fields might get destroyed. I tried to do this by moving the form to a hidden area. This made teardown work better, but I would occasionally see onReady() not firing if I did some crazy timing tests.

I ended up trying another approach, which sort of breaks the encapsulation of my component-oriented approach, but does appear to work better. In my new approach, I effectively overlay the form onto where my component should be displaying the form, where this overlay lives outside of my component which means I no longer have to move it when the component is destroyed, just hide it. Braintree seems to handle this better and I haven't yet seen onReady() not fire.

Due to the approach used by the client-side Braintree API, if you want to use it in a context where you create and/or tear it down within a single session, then it is really tricky to do this correctly if you account for all the potential asynchrony. You end up having to do some complex manage Braintree as a singleton global resource.

I don't really have a suggestion on how to improve things, since I don't really know the constraints under which you operate. However, it seems like it would be possible to devise an approach that wasn't so fragile to parallel sessions.

**Comment by lilaconlee** [comment]
@rickhall You're right, the current version of our SDK doesn't always play nicely with single page apps. We are working on making the next major version much more flexible. Hopefully you'll find it easier to work with!

**Comment by rickhall** [comment]
Thanks. Look forward to it.

**Comment by mrak** [comment]
We've released a beta of our next major version. One predominant feature of this new version is that we no longer rely on forms. All SDK actions are programmatically triggered and manually bound. Hopefully this helps with common single page application use cases.

Here are some links to our official documentation:

[Setup for v3](https://developers.braintreepayments.com/guides/client-sdk/setup/javascript/v3)
[Migrating from v2 to v3](https://developers.braintreepayments.com/guides/client-sdk/migration/javascript/v3)

Please send any beta feedback to js-sdk-beta@braintreepayments.com
