### ISSUE TITLE
input type="tel" with expiration date on iPhone

### ISSUE THREAD

**Issue by NealJMD** [braintree/braintree-web#133]
The CVV has input `type="tel"`, which summons the numeric keyboard. The numeric keyboard is great, but it doesn't have a slash. On-phone screenshot is included below for reference.

1) Are we guaranteed that submitting an expiration without a slash will in fact work?
2) Can we pass some parameter through to braintree-web to make the expiration date display use a normal keyboard? I imagine that some users when confronted with that incongruity will simply give up, because we are a non-profit soliciting donations, not selling products.

![braintree-cvv-iphone](https://cloud.githubusercontent.com/assets/102218/13241341/88ab732e-d9af-11e5-8934-54a55eddb4bf.jpg)

**Comment by lilaconlee** [comment]
Hey @NealJMD, unfortunately this is a known and expected behavior in iOS for all current versions of Hosted Fields (this has been brought up previously in #81). We accept both `MMYY` and `MM YY` formats for date, so any legitimate expiration date without a slash will be valid.

One alternative is to break your `expirationDate` into two separate `expirationMonth` and `expirationYear` fields. We know this isn't ideal and will hopefully have a nicer solution for you soon!

**Comment by skiddle** [comment]
Here's an idea Braintree - after the user has entered 2 characters (01-12) why don't you automatically insert the / for them?

That way they don't need that character on the keyboard. I've seen that done in other places and it works well.

**Comment by mrak** [comment]
@skiddle Field formatting is something that we are actively working on! Stay tuned.

See https://github.com/braintree/braintree-web/issues/77

**Comment by NealJMD** [comment]
okey-dokey. I am eagerly awaiting the field formatting - product guy is breathing down our neck about it. thanks for the response.

**Comment by scottymac** [comment]
Just ran into this and was about to contact support. Super disappointing. Doesn't it seem wrong that you'd use a Telephone type field for date entry?

**Comment by adstrakt** [comment]
We have this issue as well on a ecoommerce site and it causing sales to be lost. Is there a workaround  or when is a fix going to be released?

**Comment by scottymac** [comment]
@adstrakt I emailed BT and Tech Support wasn't much help. I ended up just removing the "/" from my expiration date field placeholder. It's not quite as intuitive, but it was an easy fix. Support told me I could also do two fields -- one for month and one for year just as @lilaconlee mentioned above.

The really issue here is that we're likely not the only ones who are losing sales because of these recent change. My guess is more people will find this thread once they realize people haven't been able to purchase using a credit card on the iPhone. 

Tech Support also suggested I follow the changelog here, but as you can see if you read it, this change was not documented (at least not that I saw).

And still I do not understand why a `telephone` field was used for credit card. Even the UI of the telephone keyboard is a bit confusing. Why not `number`?

**Comment by adstrakt** [comment]
I hope they realize this and sort it soon.

**Comment by EvanHahn** [comment]
In an ideal world, the `expirationDate` field would pull up a numeric keyboard that also had a `/` slash key, and that'd be it. Unfortunately, this is the world of web browsers, where things are rarely ideal (especially on the mobile web!).

We considered this when building Hosted Fields. There were basically four input `type`s we could've chosen:

1. `text`. This does nothing fancy on desktop browsers, but mobile browsers will bring up a normal, alphabet keyboard (with an English keyboard, anyway). We eliminated this pretty quickly, because this is not the ideal keyboard to show:

   <img src="https://cloud.githubusercontent.com/assets/777712/13926465/aeae9c36-ef49-11e5-8119-050174560679.png" width="40%" height="40%" alt='type="text" screenshot on iOS' />

1. `date` was another we eliminated quickly, because it asks for year, month, _and_ day—card expiration dates don't have a day.

1. `number`. On mobile browsers, this brings you to the numeric part of the keyboard by default, but you can navigate around and type whatever other characters you want. This is okay, but you can still type characters you shouldn't be able to type.

   <img src="https://cloud.githubusercontent.com/assets/777712/13926479/bf34fef6-ef49-11e5-8aa4-808eb6a9724b.png" width="40%" height="40%" alt='type="number" screenshot on iOS' />

   This has bad UX on modern desktop browsers, though. Check out what Chrome does:

   ![type="number" on Chrome](https://cloud.githubusercontent.com/assets/777712/13926488/ca6f6766-ef49-11e5-93f9-1a3e97b9c623.gif)

   Modern desktop browsers bring up a little number counter, which we felt was confusing—that's not something people are used to seeing in a card expiration date field.

1. `tel`, which is what we settled on. This doesn't do anything weird on desktop browsers, but it shows a keyboard that's _pretty close_ to exactly what we wanted:

   <img src="https://cloud.githubusercontent.com/assets/777712/13926497/d4006906-ef49-11e5-8226-ab2122a658d2.png" width="40%" height="40%" alt='type="tel" screenshot on iOS' />

   We felt that this was best. Our ideal world, as mentioned above, is a numeric keyboard with a slash key—this is pretty close.

The `tel` type absolutely has the disadvantage that there can be some customer confusion with the slash—we totally agree with you, @scottymac. But the `number` type has disadvantages of its own, as we discussed above.

There are two ways around this if you still don't like our decision:

1. Update your `placeholder` as @scottymac has done. If you want, you can change this placeholder dynamically based on browser:

   ```js
   braintree.setup(CLIENT_TOKEN, 'custom', {
     hostedFieds: {
        // ...
        expirationDate: {
          selector: '#bt-expiration-date',

          // Change the placeholder based on a `browserIsIos` variable you define.
          placeholder: browserIsIos ? 'MMYY' : 'MM/YY'
        }
     }
   })
   ```

1. Use a separate field for expiration month and expiration year, as @lilaconlee suggested above. Once again, you can choose to do this differently on iOS.

We're also actively working on automatic field formatting for future versions of the SDK (as @skiddle mentioned), which will automatically insert the slash. That and the fixes above will (hopefully) put this problem to rest. (Stay tuned to issue #77 for updates on field formatting.)

Hope this helps explain our decision!

**Comment by dedman** [comment]
Thanks for the comprehensive explanation @EvanHahn. Not ideal but changing the placeholder is a good enough workaround for now. 

Thanks

**Comment by lilaconlee** [comment]
@dedman As @evanhahn mentioned above, the latest version of our SDK has formatting in Hosted Fields, which includes automatic insertion of slashes in expiration dates. 

If you're interested in trying it out while it's in beta, here are some links to official documentation:

[Setup for v3](https://developers.braintreepayments.com/guides/client-sdk/setup/javascript/v3)
[Migrating from v2 to v3](https://developers.braintreepayments.com/guides/client-sdk/migration/javascript/v3)
[Hosted Fields in v3](https://developers.braintreepayments.com/guides/hosted-fields/overview/javascript/v3)
