### ISSUE TITLE
onPaymentMethodReceived doesn't fire for paypal

### ISSUE THREAD

**Issue by ivanskof** [braintree/braintree-web#134]
If using custom ui with hosted field and paypal, onPaymentMethodReceived doesn' fire after login to paypal (sandbox)
It works if using just hosted fields or just paypal (in braintree.setup()) But when using both  it doesn't fire for paypal.

**Comment by lilaconlee** [comment]
Hey @ivanskof, this is actually expected behavior when using PayPal with Hosted Fields. Because there is a credit card form, `onPaymentMethodReceived

**Comment by lilaconlee** [comment]
Hey @ivanskof, this is expected behavior when using PayPal and Hosted Fields. In this case, the `onPaymentMethodReceived` callback is not fired until the user submits a form. We understand that this behavior is a little unusual and we actually responded to a previous issue (#58) with some background and solutions.

It looks like you might want to use our `onSuccess` callback that fires upon completion of the PayPal flow. You can find an example implementation and some caveats of this approach here: https://github.com/braintree/braintree-web/issues/58#issuecomment-118852093.

Hope this solves your problem, if not feel free to reopen this issue.
