### ISSUE TITLE
onError callback returns undefined

### ISSUE THREAD

**Issue by dougjohnston** [braintree/braintree-web#138]
We are using Braintree Hosted Fields. I am seeing periodic instances of the onError callback returning an `undefined` function. Or, at least when I attempt to log the `type` and `message` from the error, I am getting `undefined` for both.

Example code from our setup file:
```
onError: function(event) {
  RS.braintree.displayErrorIfAny();
  RS.braintree.notify(event.type + ': ' + event.message, 'error');
},

// The RS.braintree calls our just calls to our custom JS to handle and log errors.
```

In this case, `event.type` and `event.message` are both coming across as `undefined`. Obviously, that doesn't give me much to go on when troubleshooting this issue. Have you seen this before and/or do you know what might be causing it?

This currently seems to be affecting maybe 2% of our customers. Of those, ~ 1/3 eventually end up completing their orders (likely through a simple refresh). The rate seems to have increased over just the last few days, so this is a growing concern.

**Comment by dougjohnston** [comment]
Also, I don't believe this is a browser related issue. I've been logging user agents on these and they're fairly diverse. Though a disproportionately high number seem to be IE 11 and MS Edge, I'm also seeing this for users on Chrome (Desktop & Android) and Safari (OSX) as well.

**Comment by lilaconlee** [comment]
This is an issue we've come across intermittently with Edge and Internet Explorer 11, and while we've seen it in other browsers, it seems to have been patched everywhere else.

Modern browsers use something called TCP preconnect to improve performance. This means the browser will often open a TCP connection with Braintree servers from your site before the user even fills out a form.

Because we have a timeout on our servers to avoid keeping open stale connections, these preconnections are often closed before the client actually needs to use them. In most browsers, they will simply reopen a new connection. Edge and IE11 have a bug where they try to reuse the already-closed connection. Because this connection has already been closed, our servers will respond with an HTTP 408 request timeout error.

We've reached out to Microsoft about this issue and are investigating potential workarounds—we'll keep you updated.

**Comment by dougjohnston** [comment]
Excellent information, thanks. That does seem like it would explain the higher rate of Edge and IE11 users.

However, I had one instance of a user earlier in week who was using Chrome 48 and Safari 9 on a Mac. I can see in the logs that, between the two browsers, they attempted to reload the payment page 27 times. Unless I'm missing something, that seems like it would not be explained by the TCP preconnect issue.

**Comment by lilaconlee** [comment]
You're right, the behavior you're seeing doesn't sound like the TCP preconnect issue. This is something that'd be easier for our support team (support@getbraintree.com) to debug with some more information about your integration. We'll make sure to follow up with them as well!

**Comment by EvanHahn** [comment]
@dougjohnston It looks like you've reached out to our support team. Is it alright if we close this issue? No problem if you'd like to keep it open.

**Comment by dougjohnston** [comment]
@EvanHahn I haven't actually followed up with Braintree support yet, but I will. You can close this issue.

**Comment by EvanHahn** [comment]
Sounds good! Feel free to reach back out if you need anything.
