### ISSUE TITLE
PayPal custom setup not returning billingAddress in `onPaymentMethodReceived` callback

### ISSUE THREAD

**Issue by dganoff** [braintree/braintree-web#146]
I have a JavaScript web app that loads a paypal button using the `braintree.setup()` method (see below) where everything seems to work fine except for retrieving the user's PayPal billing address (testing this in the Braintree Sandbox). Apparently it's supposed to return a dummy address, but I'm not getting anything.

Here's the setup code:
``` javascript
function setupPayPalButton(args, successCB, errorCB, readyCB, onCancelled) {
  var setupConfig = {
    paypal: {
      container: "paypal-container",
      singleUse: true,
      billingAgreementDescription: "Telnyx VOIP Services",
      enableBillingAddress: true,
      onCancelled: onCancelled,
    },
    onPaymentMethodReceived: successCB,
    onUnsupported: errorCB,
    onReady: readyCB,
  };

  braintree.setup(args.token, "custom", setupConfig);
}
```

Here's what I get returned to me in the `onPaymentMethodReceieved` callback:
``` javascript
{
  "nonce": "<my-nonce>",
  "details": {
    "email": "<my-email>"
  },
  "type": "PayPalAccount"
}
```

It's my understanding that the billing address should be returned inside the `details` property of the object returned in `onPaymentMethodReceived` callback.

Is there anything I've missed in this configuration? The Braintree Sandbox I'm using is setup correctly (verified by the Braintree support) for the latest PayPal flow.

**Comment by intelliot** [comment]
When using [the Checkout with PayPal flow](https://developers.braintreepayments.com/guides/paypal/checkout-with-paypal/javascript/v2#invoking-the-checkout-with-paypal-flow), `amount` and `currency` are required. Can you try adding `amount` and `currency` to your setup code?

Something like this:
```js
function setupPayPalButton(args, successCB, errorCB, readyCB, onCancelled) {
  var setupConfig = {
    paypal: {
      container: "paypal-container",
      singleUse: true,
      ...
      amount: 1.23,
      currency: "USD",
      ...
    },
    ...
  };

  braintree.setup(args.token, "custom", setupConfig);
}
```

Also, we noticed a couple unrelated potential issues:
(1) `onUnsupported` appears to be at the wrong level (it should be nested under `paypal`).
(2) The code contains trailing commas, which will work in all browsers except IE8 (this may be addressed by a minifier, if you're using one).

**Comment by dganoff** [comment]
@intelliot Thanks so much for the feedback. I was able to get the Billing Address returned from the `onPaymentMethodReceived` callback using the `amount` and `currency` fields. I just have a couple of questions regarding this setup:

1. Is this the only setup configuration that will return the Billing Address? I've spoken to the Braintree Support and they used a setup _without_ `amount` and `currency` and still got the Billing Address back.
2. Can I change the amount and/or currency after the setup has been initiated? I may want to give my users the ability to change this without waiting for the button to re-load.

Thank you!

**Comment by intelliot** [comment]
@dganoff Glad to hear that worked!

1. Another setup configuration that can return the Billing Address is to specify `singleUse: false` (or omit the `singleUse` property entirely). In this case, you will be using our [PayPal Vault flow](https://developers.braintreepayments.com/guides/paypal/vault/javascript/v2).
2. No, the amount and/or currency can't be changed after setup has been initiated. You can reduce the need for the button to re-load by using our [Custom UI](https://developers.braintreepayments.com/reference/client-reference/javascript/v2/best-practices#custom-ui) flow, but PayPal will still need to be re-loaded (and during that time, you may want to disable the button because it isn't going to work until PayPal has finished loading). I think the Vault flow could make sense for you, as it allows you to dynamically charge a different amount.

Does that help?

**Comment by intelliot** [comment]
@dganoff We haven't heard from you in a while, so we're going to close this issue.

Feel free to reach back out if we can help with anything!
