### ISSUE TITLE
Manually fire dropin-ui credit card tokenization

### ISSUE THREAD

**Issue by collizo4sky** [braintree/braintree-web#160]
By default, drop-in ui attaches itself to the form and takes over the submit event.

In our shopping card, we'll like to call a dropin-ui function to tokenize the card after our own client-side validation has been done.

```
if(no_checkout_error()) {
braintree_dropin_ui_init();
}
```

With this, we can automatically submit the form via the `onPaymentMethodReceived` event.

We need this feature asap.

**Comment by crookedneighbor** [comment]
I was about to recommend using [Hosted Fields](https://developers.braintreepayments.com/guides/hosted-fields/overview/javascript/v2) instead of Drop-In if you wanted greater control over the checkout flow, but I see that you [posted a comment in a Hosted Fields issue](https://github.com/braintree/braintree-web/issues/155#issuecomment-213891630) already.

I assume your form is structured something like this:

```html
<form>
  <input type="text" name="my_own_input_1">
  <input type="text" name="my_own_input_2">
  <div id="dropin-container"></div>
  <input type="submit" value="pay">
</form>
```

Could you keep the submit button disabled and run your client side validations on input changes? And then enable the button when the client side validations pass? 

As mentioned in #155, we're removing the dependency on form submits in the next major version of the SDK, so this should be easier to reconcile when that is released. 

I'm going to close this now, but we'll update #155 when the public beta for version 3 is released.
