### ISSUE TITLE
Missed tag v2.26.0 on GitHub

### ISSUE THREAD

**Issue by bocharsky-bw** [braintree/braintree-web#177]
Hey, looks like there's missed tag `v2.26.0` on GitHub for existing release [here](https://developers.braintreepayments.com/start/hello-client/javascript/v2#setup).

I'm wondering where can I find the latest version number?

**Comment by mrak** [comment]
You can find the latest version number from npm:

```
npm view braintree-web version
```

 or at https://github.com/braintree/braintree-web-bower, which is now used for our bower releases.

The reason for this change is we will soon be tracking v3 source releases in this repository instead of v2 built file releases.

Sorry for any confusion while we're in this middle-period. Please bear with us :)

**Comment by bocharsky-bw** [comment]
Ah, great, it helped a lot!

Thank you for the explanation!
