### ISSUE TITLE
require('braintree-web').data.setup

### ISSUE THREAD

**Issue by gato333** [braintree/braintree-web#191]
require('braintree-web').data.setup

data is now undefined 
with the new update :<

**Comment by crookedneighbor** [comment]
@gato333 I'm assuming that you were previously using version 2 which instantiated a standalone data collector instance like this:

```js
var dataCollector = require('braintree-web').data;
dataCollector.setup({
  kount: {environment: 'sandbox'},
});

dataCollector.deviceData; /* for use in transaction creation */
```

[(Full documentation here)](https://developers.braintreepayments.com/guides/advanced-fraud-tools/client-side/javascript/v2#standalone-usage)

Version 3, being a major version bump, made some changes to how data collector is instantiated. It can now be done like this:

```js
var btClient = require('braintree-web/client');
var btDataCollector = require('braintree-web/data-collector');

btClient.create({
  authorization: 'CLIENT_AUTHORIZATION'
}, function (err, clientInstance) {
  // Creation of any other components...

  btDataCollector.create({
    client: clientInstance,
    kount: true
  }, function (err, dataCollectorInstance) {
    if (err) {
      // Handle error in creation of data collector
      return;
    }
    // At this point, you should access the dataCollectorInstance.deviceData value and provide it
    // to your server, e.g. by injecting it into your form as a hidden input.
    var deviceData = dataCollectorInstance.deviceData;
  });
});
```

This method allows you to pull in only the files necessary for using data collector (the client and data-collector components) instead of all the files (Hosted Fields, PayPal, etc...). In version 2, all of those parts would have been bundled in when you built the files.

[Go here for more information.](https://developers.braintreepayments.com/guides/advanced-fraud-tools/client-side/javascript/v3)

**Comment by gato333** [comment]
Hey thanks alot for the quick response,
this is exactly what i needed.
Sorry for the brief message, 
I had a bit of a time constraint, so i just reflexively down graded to v2.~
