### ISSUE TITLE
index.js:2 require is not defined

### ISSUE THREAD

**Issue by Bennit** [braintree/braintree-web#194]
I'm using the braintree SDK in an angular 1.5.x application. I installed the SDK a long time ago via bower; and as of the 3.x.x release, you seem to be working with requirejs; causing my browser to complain about require not being defined. Did you guys forget a dependency by any chance? In 2.27.0 it is still working without any interference.

Kind regards
Ben

**Comment by crookedneighbor** [comment]
As of version 3, the sdk is completely modular. Instead of using the index.js file, you would use the specific components you need for your integration. For instance, if you are using hosted fields, you'd use the [client component](https://github.com/braintree/braintree-web-bower/blob/master/client.js) and the [hosted fields component](https://github.com/braintree/braintree-web-bower/blob/master/hosted-fields.js). The setup section for [direct links](https://developers.braintreepayments.com/guides/client-sdk/setup/javascript/v3#use-the-direct-links) makes that more obvious. This allows you to keep your file sizes small, so you only pull in the code you need for your project. 

You would only use the index.js file if you were using a build tool such as [Browserify](http://browserify.org/) or [Webpack](https://webpack.github.io/). 

We will update the [install with Bower](https://developers.braintreepayments.com/guides/client-sdk/setup/javascript/v3#install-with-bower) section of our docs to make this more clear.

**Comment by crookedneighbor** [comment]
@Bennit Here is the updated documentation: https://developers.braintreepayments.com/guides/client-sdk/setup/javascript/v3#install-with-bower

**Comment by Bennit** [comment]
@crookedneighbor thanks a lot!
