### ISSUE TITLE
hosted fields - v3 validation classes

### ISSUE THREAD

**Issue by bob2021** [braintree/braintree-web#196]
Using the v2 sdk, when an invalid field is submitted then the class `braintree-hosted-fields-invalid` is added to the field's container.   I expected the same thing to happen with the v3 sdk when tokenize() is called, but it doesn't.  

Is this a bug or should I be using the error data in the tokenize callback to add the classes myself?

**Comment by crookedneighbor** [comment]
In version 3, we decided to give the developer complete control over these kinds of situations because there were some cases that were ambiguous.

So there are a couple of ways you can do this. You can [check the state](http://braintree.github.io/braintree-web/current/HostedFields.html#getState) _before_ tokenizing.

```js
var fields = hostedFieldsInstance.getState().fields;
var isValid = Object.keys(fields).every(function (field) {
  return fields[field].isValid;
});

if (isValid) {
  // tokenize
} else {
  // handle invalid fields
}
```

You can check using the errors from the [tokenize method](http://braintree.github.io/braintree-web/current/HostedFields.html#tokenize).

```js
hostedFieldsInstance.tokenize(function (err, payload) {
  if (err) {
    if (err.code === 'HOSTED_FIELDS_FIELDS_EMPTY') {
      // display message that all fields are empty
      // add error class to all fields
    } else if (err.code === 'HOSTED_FIELDS_FIELDS_INVALID') {
      var invalidFields = err.details.invalidFieldKeys;
      invalidFields.forEach(function (field) {
        // look up dom node associated with field
        // apply error class to invalid field
      });
    } else {
      // handle other error
    }
    return;
  }

  // Submit payload to server
});
```

Note, if you check the state before hand, you will still want to check errors from the tokenize call. For example, in the case that someone mistypes in their credit card and it passes the [Luhn 10 check](https://en.wikipedia.org/wiki/Luhn_algorithm), but is not actually a valid credit card.

**Comment by ylin6** [comment]
is there any way we can add custom inline error messages to the field?

**Comment by crookedneighbor** [comment]
Yes. In the section that says

```
// look up dom node associated with field
// apply error class to invalid field
```

You can, in addition, add text to the an element near the field.
