### ISSUE TITLE
Drop-in callbacks aren't fired

### ISSUE THREAD

**Issue by Tyrdall** [braintree/braintree-web#199]
We got some issues, especially with PayPal. For example, sometimes the PayPal authorization windows goes blank and users cancel their orders.

Now, I want to track every single error or cancellation, which happens during the checkout. But some callbacks are never fired.

    braintree.setup(token, "dropin", {
        container: "foo"
        ,onError: function (error) {
            // Works great!
        }
        ,onReady: function () {
            // Works great!
        }
        ,onPaymentMethodReceived: function (obj) {
            // Only fired by submitting the whole form. Not really helpful.
        }
        ,paypal: {
            onUnsupported: function () {
                // Never fired.
            }
            ,onCancelled: function () {
                // Never fired.
            }
            ,onAuthorizationDismissed: function () {
                // Never fired.
            }
        }
    });

Any ideas?

**Comment by crookedneighbor** [comment]
Have you noticed any patterns for when the popup window does not display? IE, is it always in a particular browser?

**Comment by crookedneighbor** [comment]
@Tyrdall ^

**Comment by Tyrdall** [comment]
@crookedneighbor Sorry for the misunderstanding. The blank PayPal window is part of https://github.com/braintree/braintree-web/issues/166.

This issue is about the callbacks, which aren't fired.

**Comment by mrak** [comment]
Here's an explanation of the PayPal callbacks you mentioned:

* `onUnsupported` - fired when you attempt `braintree.setup` with paypal options, but they browser is not supported by PayPal.
* `onCancelled` - fired when a user has already logged in to paypal and completed the popup authentication flow, then clicks the `cancel` link next to their email address in the UI element that has since replaced the PayPal button.
* `onAuthorizationDismissed` - fired when a user closes the PayPal auth popup prematurely, or has clicked a cancellation link _within_ the popup flow.

In regard to other error scenarios such as the popup going blank, it may not fire any error callbacks. We're currently investigating the issues described in #166.

**Comment by Tyrdall** [comment]
@mrak Thanks for the explanation. The ``onAuthorizationDismissed`` event is what I'm looking for. Unfortunately I'm not able to get it to work. It doesn't get fired, if I close the PayPal window or if I click on "Cancel" within the window. Any advice?

**Comment by mrak** [comment]
However, our Drop-in integrations do not fire the paypal-specific callbacks.

Our documentation does not mention this fact -- we will get this corrected. Sorry for any confusion.
