### ISSUE TITLE
3dsecure does not set currency

### ISSUE THREAD

**Issue by HZ-labs** [braintree/braintree-web#205]
I try to change the currency for 3d secure, but in the modal window we get only USD. In the documentation I can't find anything about this. I try to use this code
    
    client.verify3DS({
        amount: 180,
        currency: "GBP",
        creditCard: {...}
    }, function (error, response) {
        // Handle response
    })

client-sdk: v2

**Comment by crookedneighbor** [comment]
Currency is determined automatically by your processor settings from the merchant account id used to generate your client token. Since the processor settings for that merchant are set to process USD, the amount will be in usd. To change the currency, you'll need to create a new merchant account with a different currency in its processor settings.

![merchant account](https://cloud.githubusercontent.com/assets/2916945/18315621/41d8ea98-74dd-11e6-81a5-f8a7eedba394.png)
