### ISSUE TITLE
Hosted Fields Formatting broken on mobile

### ISSUE THREAD

**Issue by eatpurely** [braintree/braintree-web#212]
When using hosted fields, the fields will not format correctly on mobile devices. When entering Card numbers, this is not a huge issues, but the larger issue is that the expiration field does not do any type of formatting either.

This can be replicated on iOS Safari and also seen in Google Chrome Simulator.

Thanks,

Dan

**Comment by Algeroth84** [comment]
Experienced same problem after moving to client sdk 3.1.0. I tried even using 
				expirationDate: {
					selector: '#expiration-date',

				}

**Comment by Algeroth84** [comment]
Same problem for me after migration from v2 to 3.1.0 of javascript client. Since it's automatically disabled on Android and IOS browsers I'd expect also validation for typing "/" character was disabled but it is not.
I tried to set 
				expirationDate: {
					selector: '#expiration-date',
					formatInput: false
				}
but I got the same validation problem. The only way to go through is using a format like 'MMYY' and no / character.

**Comment by crookedneighbor** [comment]
Formatting is intentionally disabled in mobile devices because it currently has some glitchy behavior.

We're very close to solving the issue [see this Pull Request](https://github.com/braintree/restricted-input/pull/13). If all goes as planned, we'll be able to enable mobile formatting in the next release.

`/` is actually not required in expiration date. Typing `122019` will be interpreted as `12/2019` when tokenizing. If it helps, you can also split up the expiration date into two fields, [one for month and one for year](https://braintree.github.io/braintree-web/3.1.0/module-braintree-web_hosted-fields.html#.create).

@Algeroth84 To your point, I think you have uncovered a bug. Hosted fields should not care about the presence of `/` in an expiration date input that is not auto-formatted. We'll look into that.

**Comment by Shaneprrlt** [comment]
How close are you from fixing the `/` formatting problem for month/year?

**Comment by crookedneighbor** [comment]
Just fixed it, will probably go out in the next release.

**Comment by eatpurely** [comment]
Perfect, thanks!

**Comment by crookedneighbor** [comment]
`braintree-web@3.2.0` will not display the `expirationDate` field as invalid for having a space, hyphen or slash when the field has formatting turned off.

We're still hard at work fixing formatting on mobile—that's coming!

**Comment by mrak** [comment]
We have released `braintree-web@3.3.0` with formatting enabled for iOS devices.

Unfortunately, we are still working through formatting issues on Android browsers and keyboards.

**Comment by crookedneighbor** [comment]
Formatting has been enabled for Android devices in `braintree-web@3.4.0`
