### ISSUE TITLE
Braintree Sandbox Creditcard Tokenize (v3 JS SDK)

### ISSUE THREAD

**Issue by aight8** [braintree/braintree-web#213]
**Code:**
```JS
      this.clientInstance.request({
        endpoint: 'payment_methods/credit_cards',
        method: 'post',
        data: {
          creditCard: {
            ...data.card,
          }
        }
      }, function (err, response) {
        if (err) {
          console.error(err);
          reject(err);
          return;
        }

        resolve();
        console.log(response);
      });
    });
  }
```

**Response:**
```JSON
{"error":{"message":"User does not have the required permissions for this action"},"fieldErrors":[]}
```

**Comment by crookedneighbor** [comment]
Unfortunately, that error does not necessarily indicate an error with your permissions. It can also be returned if you pass incorrect properties in the data object.

What properties are you passing in for `creditCard`? My guess is you're sending something incorrectly there (like sending `postalCode` at the top level instead of sending it nested under a `billingAddress` object or misspelling `expirationDate`).

It should look something like this:

```js
var form = document.getElementById('my-form-id');
var data = {
  creditCard: {
    number: form['cc-number'].value,
    cvv: form['cc-cvv'].value,
    expirationDate: form['cc-date'].value,
    billingAddress: {
      postalCode: form['cc-postal'].value
    }
  }
};

clientInstance.request({
  endpoint: 'payment_methods/credit_cards',
  method: 'post',
  data: data
}, function (requestErr, response) {
  // handle error and response
});
```

http://braintree.github.io/braintree-web/current/Client.html#request

**Comment by aight8** [comment]
I see, I passed the "fullName" field in the creditCard object that's caused this error. Was a little bit confusing. Thank you.
