### ISSUE TITLE
Error docs

### ISSUE THREAD

**Issue by jackocnr** [braintree/braintree-web#223]
Hi there! Is there any documentation on the structure/contents of the error object that gets passed to the callback when you use various methods in the JS SDK v3? Specifically, we're using the `braintreeClient.request` method for credit card submissions, and the `paypalInstance.tokenize` method for Paypal.

I found [this page on BraintreeError](https://braintree.github.io/braintree-web/3.3.0/BraintreeError.html), which tells you the names of the different error types, but doesn't tell you anything about what you can expect in the `details` object.

If I call `braintreeClient.request` and send erroneous credit card data, I can manually inspect the `requestErr` error object that gets passed to the callback, and it seems like I can access the first field-specific error message like this: `requestErr.details.originalError.fieldErrors[0].fieldErrors[0].message`. Is that the best way to do it, or is there a more standard way to access this information using the SDK? I'm concerned about relying on this structure explicitly considering I can't find any documentation around it. And also does it differ in different situations/contexts e.g. a PayPal request?

Finally, do these error messages have localization support, and if so, how does it know what locale to use, and is there an easy way to test this?

Thanks a lot for your help :)

**Comment by skunkworks** [comment]
Hi @jackocnr,

We do not have any external documentation for the format of these error responses from the Braintree gateway when doing card tokenization with the BraintreeClient. The method with which you receive the field-level errors is correct -- you can reliably expect the format to be future-proof, especially since our own Drop-in products on JS/Android/iOS do the same response parsing you are.

The error messages from PayPal will differ in the sense that there's no sense of field-level errors in that context. PayPal errors may have `details.originalError` to get more information about what went wrong.

`BraintreeError` messages are not localized, so the recommended approach is to interpret the error codes (`error.code`) and display your own localized error message.

Hope that helps!

**Comment by jackocnr** [comment]
Thanks for your response.

In case it helps others, here's a list of all [Validation Errors](https://developers.braintreepayments.com/reference/general/validation-errors/all/ruby) including error codes.

**Comment by crookedneighbor** [comment]
Those validation errors are for the server side SDKs, I don't see any that correspond to the client requests.

**Comment by jackocnr** [comment]
Well if I submit a credit card number of 5555555555555555 then I receive the error code 81715 with the message "Credit card number is invalid", so that one seems to match.

Perhaps @skunkworks can confirm if these errors also apply to the client requests or not?

**Comment by skunkworks** [comment]
@jackocnr As you may have noticed already, the field error codes are correlated with a small subset of the error codes from the [Validation Errors](https://developers.braintreepayments.com/reference/general/validation-errors/all#credit-card) documentation. This is the case when you are tokenizing and validating a card and the gateway returns a validation error response.

However, as @crookedneighbor mentioned, the vast majority of those errors don't apply to the client-side APIs or SDKs.

**Comment by jackocnr** [comment]
@skunkworks ok thanks. So is there no way to know which errors we have to handle when performing client requests?

**Comment by skunkworks** [comment]
@jackocnr For now, yes, the error responses when hitting the card tokenization endpoint does not have crystal-clear documentation around what errors you should expect to handle. The validation errors documentation linked previously is very useful, however.

Right now we do not have clear documentation for advanced client integrations that hit bare-metal API endpoints. [Hosted Fields](https://developers.braintreepayments.com/guides/hosted-fields/overview/javascript/v3) provides clearer expectations around its API, if it meets your requirements.

**Comment by jackocnr** [comment]
@skunkworks yes we would like to move to Hosted Fields at some point, but can you explain how localization would be easier if we did implement Hosted Fields? AFAICS the error handling is exactly the same?

**Comment by skunkworks** [comment]
Hosted Fields has a lot of built-in client-side validation that should reduce the number of error cases you have to handle (e.g. CVV missing, invalid expiration dates), but you are correct that if you are vaulting credit cards (validating card numbers) that you will still have to handle some number of errors yourself (e.g. card fails validation due to invalid CVV, have to present a localized error message).

**Comment by jackocnr** [comment]
Thanks for your help. Can I ask: is it on the roadmap to document the list of errors you have to handle on the client?

**Comment by skunkworks** [comment]
Absolutely! I'll bring it up at our next meeting.

**Comment by jackocnr** [comment]
Great. Thanks again.
