### ISSUE TITLE
Disable dropin-UI if amount is zero or some other business rules apply(like wallet balance)

### ISSUE THREAD

**Issue by abhijeetahuja** [braintree/braintree-web#236]
Is there any way to disable/hide dropin-ui form if I don't want to accept payment like in cases if the calculated amount is zero or if user wants to pay by wallet balance?

**Comment by abhijeetahuja** [comment]
is teardown the solution?

**Comment by DaveMacaulay** [comment]
This is more down to your integration rather than a braintree-web issue. Your business logic should dictate whether or not the Braintree drop-in UI should be initialised. If your rules determine it shouldn't you'd simply need to display an alternative method of progressing through your checkout.

**Comment by crookedneighbor** [comment]
@DaveMacaulay is correct. This should be entirely in your control to hide or display the Drop-In UI.

I recommend contacting support@braintreepayments.com if you need assistance with your integration.

**Comment by gerrywastaken** [comment]
@DaveMacaulay @crookedneighbor I'm wondering the same thing. Say for instance there are payment methods outside of Braintree on the same page. If the user pays all of the order outside of the Braintree component then it would need to be unhooked at that point. There is no page refresh which can then decide to not initialise the Braintree drop-in UI.

The user may want to pay using Braintree, they may want to pay using the alternative method or they may part pay on the alternative method and then the remainder on Braintree. This is not known at initial page render. I believe this was the same situation @abhijeetahuja was facing and he asked if `teardown` was an appropriate solution, but did not get an answer to that question.

**Comment by DaveMacaulay** [comment]
@gerrywastaken I had the same situation when I built the Magento 1 plugin for Braintree. As the entirety of the checkout is Ajax there aren't any page loads, so naturally we had to destroy (teardown) & rebuild the plugin based on user interaction. It's relatively straight forward to implement using a simple events system connected to your integration.

I didn't see any detrimental impact on the browser, both operations are relatively efficient. Teardown will also remove all of the associated events meaning the user is free to continue through their other selected payment method. If you wanted to do partial payments through Braintree you'd need to bake that into your integration rather than Braintree's side being able to facilitate this. E.g. request payment from one source and then the other.

So in answer to yours and @abhijeetahuja question I'd say teardown is suitable for this operation.
