### ISSUE TITLE
Number formatting in hosted fields - Safari 5.x

### ISSUE THREAD

**Issue by jobbrown** [braintree/braintree-web#237]
First off I appreciate Safari 5.x is out of the supported range but I think a quick fix here could solve some limited headaches for all of us.

In short, when typing in a card number in Safari 5.x the numbers will be jumbled up after the first four. Attempting to type in `4123 1234 5678 1234` will result in `4123 4321 8765 4321` (after the first four it types right to left). We've had a few reports of this but this is the first we've been able to replicate. 

Disabling `formatInput` on those fields rectifies the issues. I can see this is already disabled on Android / iOS. 

Is it possible to disable it on older versions of Safari too?

**Comment by crookedneighbor** [comment]
Input formatting is no longer disabled for iOS ([v3.3.0](https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md#330)) and Android ([v3.4.0](https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md#340)).

Since we don't support Safari 5.x, we will not be adding that logic. However, you can detect if your user is using Safari 5.x and conditionally apply `formatInput: false` if that is the case.
