### ISSUE TITLE
Hosted Fields - Postal Code Validation During Tokenization

### ISSUE THREAD

**Issue by paymentplugins** [braintree/braintree-web#242]
If AVS checks for postal code are enabled within the Braintree Control Panel, then the postalCode attribute of the billing array (PHP) is used during the transaction sale call to perform validations. V3 of the hosted fields js library allows you to setup a postal field input field as well. When testing in production, as long as you enter a valid postal code field for the transaction sale call, then you can enter any number you want for the hosted postal code field client side and the transaction will pass withput error. This is similar to issue 235 but I am wondering what the purpose of the postal-code hosted field is for? Is it only used for validations if the vault = true attribute is passed during tokenization?

Kind Regards,

**Comment by quinnjn** [comment]
It sounds like the customer is entering a postal code in Hosted Fields, and then you are also providing a postal code at transaction sale time. If this is the case the postal code used at transaction sale will be used rather than the client side one from Hosted Fields.

If you tokenize with `vault = true`, then verification will happen on the client side and the AVS checks should trigger if the postal code does not match.

If this didn't answer your question please feel free to re-open this issue with a rephrased question.
