### ISSUE TITLE
3.8.0 broke for webpack ignore

### ISSUE THREAD

**Issue by chadhahn** [braintree/braintree-web#260]
3.8.0 just broke every webpack build that uses 'noParse: [/braintree-web/],' which was the fix to ignore braintree/webpack errors in the console.

**Comment by crookedneighbor** [comment]
3.8.0 now puts the unbundled code on npm, so the `noParse` hack is no longer needed. The reason it breaks is because now webpack _needs_ to parse it.

I'm going to leave this open for a few days so other people using webpack with the `noParse` hack will be able to see the solution, then we will close this issue.

**Comment by jeerbl** [comment]
+1

Removing the `noParse` for `braintree-web` fixed the issue.
