### ISSUE TITLE
SFSafari​View​Controller - Paypal hangs on loading spinner

### ISSUE THREAD

**Issue by dansl** [braintree/braintree-web#273]
### General information

* SDK version: 3.11.0
* Environment: Production
* Browser and OS: SFSafari​View​Controller - iOS 10.2

### Issue description

When trying to initiate Paypal via a SFSafari​View​Controller, it will just hang on the loading spinner and will never move on. It works via Safari app though.

![screen shot 2017-03-15 at 4 00 38 pm](https://cloud.githubusercontent.com/assets/139961/23970656/90b7cf3a-0998-11e7-9f71-ce6b82ef7cdf.png)

**Comment by dansl** [comment]
Looks like it's getting stuck on this page. https://checkout.paypal.com/web/3.11.0/html/paypal-landing-frame.min.html if that helps

**Comment by crookedneighbor** [comment]
The problem here is that the Safari View controller presents itself to the SDK like a regular safari page, with full popup support. The reality is that although it does open up the new window, it loses the context of the original page and cannot communicate back with it so it knows to redirect to the PayPal login page, and then, ultimately, back to the original page.

To my knowledge, there's no way for us to tell if the window we're opening is inside a regular Safari page, or a view controller. 

We wrote a library called [Popup Bridge](https://github.com/braintree/popup-bridge-ios) to facilitate this gap and allow you to use our [native iOS SDK](https://github.com/braintree/braintree_ios) to open the PayPal login in real Safari window from the view controller. v3.9.0 and higher of braintree-web support this.

**Comment by dansl** [comment]
Thanks for the info. Sucks Apple doesn't give us a way of detecting the Safari View controller.

**Comment by intelliot** [comment]
@dansl To clarify - if your website is being loaded in a Safari View Controller, then braintree-web won't work there. PopupBridge works with pages loaded in a WKWebView.

So, depending on why the site is in a SFSafari​View​Controller to begin with, there are a few options:

1) Use a WKWebView instead of a SFSafariViewController. Then you can use PopupBridge for iOS with braintree-web v3.9.0 and higher.
2) Use the native Braintree iOS SDK. Then you don't use braintree-web at all, and your app can accept PayPal.
3) If the Safari View Controller is entirely outside your control (e.g. it's within someone else's app), then there's nothing we can do until Apple gives us a way of detecting the Safari View Controller. I've [filed a bug with Apple](https://bugreport.apple.com/) (rdar://31117000) for this issue; feel free to create an additional one, since I'm told that Apple prioritizes issues that get reported by multiple people.

Does this help?

**Comment by dansl** [comment]
Yes, thanks for all the help. Our site offers ApplePay, so unfortunately WebView isn't an option... Were just going to take them to the Safari app for now until we can get native iOS integrations in place. I will also file a bug with Apple to help them prioritize it 👍 

Do you want me to leave this issue open?

**Comment by intelliot** [comment]
You're welcome!
