### ISSUE TITLE
[Question] Paypal UI/UX example

### ISSUE THREAD

**Issue by muhammad-ammar** [braintree/braintree-web#274]
Hi,

Do we have any Paypal UI example code like we have for [hosted fields](https://developers.braintreepayments.com/guides/hosted-fields/examples/javascript/v3). This is the first time i am working on braintree and currently i only see Mock Sandbox Purchase Flow popup.  How the popup will look like in production? What to render on UI after popup is closed? Hosted fields are clear about this but i am confused regarding how the paypal UI looks like for whole flow?

**Comment by skunkworks** [comment]
@muhammad-ammar In the Braintree Control Panel, you can add your [PayPal Sandbox API credentials](https://developer.paypal.com/docs/classic/lifecycle/sb_credentials/) (email, client ID, client secret) to your PayPal processing options, and that will connect your Braintree account to use your PayPal developer account. This gives you the full PayPal Sandbox experience rather than the "Mock Sandbox Purchase Flow", and it looks and feels like the production experience.

When you receive the PayPal tokenization response, one option would be to display the PayPal account email address, which comes back as part of the [tokenization payload](https://braintree.github.io/braintree-web/current/PayPal.html#~tokenizePayload).

Let me know if that helps.

**Comment by muhammad-ammar** [comment]
@skunkworks Unfortunately i don't any options in in braintree control panel where i can add PayPal sandbox API credentials. Am i missing something?

**Comment by skunkworks** [comment]
@muhammad-ammar Sorry about that -- our [support team](https://developers.braintreepayments.com/forms/contact) can link those credentials to your Braintree account.

I forgot that only Braintree accounts have authorization to add those in the Control Panel.

**Comment by muhammad-ammar** [comment]
@skunkworks I will send an email to support team. What should tell them? Link my PayPal developer account with braintree?

**Comment by skunkworks** [comment]
Correct 👍

In the near future, this is something you should be able to do yourself through the Control Panel, but as of today it's something that requires us to configure on your behalf.

**Comment by muhammad-ammar** [comment]
Thanks @skunkworks
