### ISSUE TITLE
Input goes right-to-left after 4 digits for card number hosted field on Android

### ISSUE THREAD

**Issue by jfillbrook** [braintree/braintree-web#284]
### General information

* SDK version: 3.6.2
* Environment: Production
* Browser and OS: Chrome, Android 6, Samsung Keyboard, SM-T550

### Issue description

When using the card number hosted field on the tablet above, there is an input issue.

1. You can type the first 4 digits as usual
2. Then when you type the 5th, it adds in a space and the digit. But it also moves the cursor to the left of the digit.
3. If you carry on adding in more digits, they all appear in a right to left format past the first 4
4. If you instead move the cursor back to the right, the same behaviour just happens for each subsequent digit, so it's too hard to use on this device

**Comment by crookedneighbor** [comment]
There have been numerous fixes for input formatting on Android devices since v3.6.2. If you upgrade to the latest version (3.12.0 as of this writing), do you still have this issue?

Just a note, there is a [slight PayPal bug](https://github.com/braintree/braintree-web/issues/282) in 3.12.0. We are planning on releasing a patch release today to fix it, so if you're using PayPal in your integration, you may want to wait till that goes out to upgrade your integration in production. I'll post here when it is released.

**Comment by jfillbrook** [comment]
Version 3.12.0 resolves the issue for us. 

Thanks for the warning about PayPal. We're using it so we'll wait until the new release.

**Comment by quinnjn** [comment]
@jfillbrook We just released [3.12.1](https://github.com/braintree/braintree-web/blob/3.12.1/CHANGELOG.md#3121) which fixes PayPal not detecting the popup being closed.

You should be 👍  to upgrade. Closing this issue.
