### ISSUE TITLE
paypal-checkout

### ISSUE THREAD

**Issue by maxisam** [braintree/braintree-web#304]
It seems like in paypal-checkout solution,
we always need to use paypal-checkout to render the button to trigger tokenization.

Is there a different way to do it like old paypal solution that we can just call tokenize function to get the nonce?

### General information

* SDK version: 3.18.0

**Comment by quinnjn** [comment]
At this time there isn't an equivalent of `braintree.paypal.tokenize`.

The Braintree PayPalCheckout component delegates more than button rendering to [PayPal Checkout](https://github.com/paypal/paypal-checkout). PayPal Checkout takes care of opening and managing the popup as well. The Braintree PayPalCheckout component just handles the interaction with Braintree. 

You would have to delegate some PayPal Checkout's callbacks to the Braintree PayPalCheckout component. 

You can view a [simple PayPalCheckout integration](https://developers.braintreepayments.com/guides/paypal/client-side/javascript/v3#initialize-components) on our developer site to get started.

I'm going to close this issue, reopen it if you would like to further discuss!

**Comment by maxisam** [comment]
It actually loses a lot of flexibility in term of design. It forces us to accept the style of PayPal. I mean it is 2017. Everyone uses flat design. 

Any timeline that Braintree PayPal will stop supporting?

**Comment by quinnjn** [comment]
If the concern is the PayPal Checkout button design, you should open an issue on [PayPal Checkout](https://github.com/paypal/paypal-checkout).

I don't have a timeline for when Braintree will stop supporting the `braintree.paypal` at this time.

**Comment by maxisam** [comment]
I actually did. The concern is not just Paypal button design. It limits the options to integrate with the existing system.  I wonder how many people would get on board with new Paypal Checkout if they know this.

**Comment by skunkworks** [comment]
@maxisam, I understand your concerns about delegating UI to the PP Checkout SDK.

The PP checkout.js SDK implements a lot of what we think are UI/UX best practices so that you don't have to. In addition, it is standard practice for payments brands to encourage or enforce UI branding guidelines: Apple Pay, Visa Checkout, and Masterpass are some examples of payment wallets that expect merchants to use specific assets for their buttons.

We cannot promise that the `paypal` component in the Braintree SDK will be supported indefinitely, but our informal policy is to support products as long as they are used by merchants until it becomes either highly impractical or impossible. For example, v2 of the JS SDK still receives minor updates and bug fixes despite v3 being released over a year ago. I hope that works for you.
