### ISSUE TITLE
Dropin UI , data-collector implementation error

### ISSUE THREAD

**Issue by lianglee** [braintree/braintree-web#323]
### General information

* SDK version: 3.22.2
* Environment: Sandbox
* Browser and OS All browsers,  Windows 8.1 x64

### Getting error when setting up data-collector

Code used : https://gist.github.com/lianglee/4b1de3c7605f06ba4ff6c3e45dc346a3
Device data isn't working, getting following error in console: 

![image](https://user-images.githubusercontent.com/805066/30001226-d0e95a76-90a0-11e7-9746-0a7410174df2.png)

**Comment by haraldpdl** [comment]
DataCollector has been added to Drop-In in v1.7.0. This can be used in your sample as:

```
braintree.dropin.create({
  authorization: '<?php echo $token;?>',
  container: '#dropin-container',
  paypal: {
    flow: 'vault'
  },
  dataCollector: {
    kount: true,
    paypal: true
  }
}, ..
```

The DataCollector value is returned in the requestPaymentMethod payload, eg:

```
instance.requestPaymentMethod(function(requestPaymentMethodErr, payload) {
  $('.nonce').val(payload.nonce);
  $('#dataCollectorInput').val(payload.deviceData); // add this hidden input to your form
  $('#checkout').submit();
});
```

including the data-collector.min.js file is not necessary as Drop-In takes care of this automatically.

**Comment by crookedneighbor** [comment]
@haraldpdl is correct that v1.7.0 now includes Data Collector built into Drop-in.

The reason your code sample did not work is because you were passing the drop-in instance into the data collector create, rather than creating a client and passing the client into data collector create.

Going to close this now, but feel free to comment if your issue is not resolved.

**Comment by lianglee** [comment]
thanks!
