### ISSUE TITLE
How do I know when hosted field are ready?

### ISSUE THREAD

**Issue by Piero87** [braintree/braintree-web#330]
Hi,
How do I know when hosted field are ready? This is my code:

```
braintree.client.create({
          
          authorization: braintree_client_token
        }, function (clientErr, clientInstance) {
          if (clientErr) {
            console.log(clientErr);
            return;
          }
        
          braintree.hostedFields.create({
            client: clientInstance,
            styles: {
              'input': {
                'font-size': '14px',
                'font-family': 'helvetica, tahoma, calibri, sans-serif',
                'color': '#3a3a3a'
              },
              ':focus': {
                'color': 'black'
              }
            },
            fields: {
              number: {
                selector: '#card-number',
                placeholder: '**** **** **** ****'
              },
              cvv: {
                selector: '#card-cvc',
                placeholder: "CVC"
              },
              expirationDate: {
                selector: '#card-expiry',
                placeholder: "EXPIRY"
              }
            }
          }, function (hostedFieldsErr, hostedFieldsInstance) {
            if (hostedFieldsErr) {
              console.log(hostedFieldsErr);
              return;
            }
            
HERE THE FIELD ARE NOT READY

}....
```

In the callback of the hosted field are not ready yet, how I can do?

**Comment by crookedneighbor** [comment]
Can you elaborate about what you mean that they are not ready? The hosted fields create callback should not be called until after the fields are completely set up and ready to be used.

**Comment by Piero87** [comment]
Sure, If I put a debugger in the line where I write this: **HERE THE FIELD ARE NOT READY** and I look with the inspector the page I see this:

<img width="525" alt="schermata 2017-10-24 alle 16 05 55" src="https://user-images.githubusercontent.com/768952/31947815-7ea0c59e-b8d5-11e7-8e68-191c05a4c43c.png">

Instead if JUMP the debugger I see this:

<img width="531" alt="schermata 2017-10-24 alle 16 06 22" src="https://user-images.githubusercontent.com/768952/31947843-91faada8-b8d5-11e7-8536-57e74c6e37bc.png">

So as you can see in the point where I write this: **HERE THE FIELD ARE NOT READY** the input element is not ready yet. I need to attach the input element to this library:

https://github.com/jessepollak/card

but doesn't work because I don't know where initialize it

**Comment by Piero87** [comment]
I can't figure out how I can use this library: https://github.com/jessepollak/card with Braintree web, anyone can help me?

**Comment by crookedneighbor** [comment]
There may be a very slight delay between when the callback is called and the iframes are finished loading. We'll work to correct that, if possible.

In regard to that 3rd party library, you cannot use it with hosted fields. The credit card data is encapsulated inside an iframe, which takes the PCI burden off of you the merchant. This means that the data in the iframes is not directly accessible, so it cannot be passed to that 3rd party library.

You _could_ do [direct tokenization with braintree-web](http://braintree.github.io/braintree-web/current/Client.html#request-examples) using the client component, but this requires a much greater degree of SAQ A compliance since the raw card details would be on your domain instead of inside Braintree's iframes.

I'm going to leave this open, because I believe you are correct that there is a slight delay where the inputs are not actually set up yet when the callback is called.

**Comment by crookedneighbor** [comment]
We did a little exploration of this, and in my testing, putting a breakpoint in the callback still allowed the fields to be rendered immediately. It's possible there is a fraction of a second delay, but as the fields cannot be manipulated anyway, and there should be little or no discernible delay to the user, I'm going to close this.
