### ISSUE TITLE
Possible to specify recurring payment plan_id with checkout window?

### ISSUE THREAD

**Issue by mobitar** [braintree/braintree-web#340]
I'm using the v3 vault flow to authorize a payment for a subscription. However, I'm not able to find any documentation on whether it's possible to show the user what they will be paying and the payment frequency. Instead it shows only:

<img width="451" alt="screen shot 2017-12-07 at 1 14 19 pm" src="https://user-images.githubusercontent.com/3277844/33733926-e6ebaa86-db50-11e7-9d27-5bf4f434f27b.png">

Is it possible to display payment amount + frequency for recurring payment plans?

**Comment by mobitar** [comment]
It also says at the bottom "You’ll be able to review your order before you complete your purchase." but this is not the case. After I hit Agree & Continue, the window closes and I receive a payment nonce and charge the user.

**Comment by crookedneighbor** [comment]
There isn't a way to display the amount with the vault flow via the PayPal Billing Agreement API. This is because with Billing Agreements, the merchant is in *full control* of when to bill and for how much. It's not actually a recurring system, and legally, PayPal needs to inform the customer that they are giving the permissions for the merchant to charge at any time.

So even if the payment method is used within a recurring billing system, the way PayPal's API works, there's no way to specify that.

The text about `You’ll be able to review your order before you complete your purchase.` does seem like a mistake. The team that handles the login flow is here: https://github.com/paypal/paypal-checkout/issues

Feel free to open up an issue with them so they can investigate/update the text.

**Comment by mobitar** [comment]
Ok, will take it up with them. But just to make sure, when you say the merchant is in full control, PayPal will still handle recurring payments automatically, right? I'm talking about creating a subscription like this:

``` ruby
sub_result = Braintree::Subscription.create(
  :payment_method_token => token,
  :plan_id => "monthly"
)
```

I don't have to charge this user after a month, PayPal will do it for me, right?

**Comment by crookedneighbor** [comment]
^ That is through Braintree's recurring billing system. Braintree is using PayPal's Billing Agreements API to facilitate it.

So yes, the Braintree subscription will charge the customer's PayPal account on a recurring basis.
