### ISSUE TITLE
Drop-in UI: additional callbacks

### ISSUE THREAD

**Issue by jabosolutiony** [braintree/braintree-web#37]
It seems like there aren't any callbacks when a new payment method has been created from drop-in UI. Are there any plans on adding this callback?

**Comment by kyledetella** [comment]
@jabosolutiony you are correct, we do not message anything out when payment methods are created. I am going to bring this up with the team and I will get back to you. Thanks for raising the issue!

**Comment by istolga** [comment]
+1

**Comment by ppcano** [comment]
@kyledetella +1, any plans?

**Comment by TheLudd** [comment]
We would also appreciate this. We sometimes use the form only to add an extra payment method and it seems strange to force an extra click in our interface. We cannot give any feedback to the user that the add was successful.

**Comment by EvanHahn** [comment]
Sorry to have left this for so long—things got away from us.

Drop-in (and all other braintree.js integrations) supports three callbacks:

1. [`onReady`](https://developers.braintreepayments.com/javascript+node/guides/client-sdk#global-setup), which is called when the customer can start typing.

2. [`onError`](https://developers.braintreepayments.com/javascript+node/guides/drop-in#onerror), which is called when errors happen in the system. These can happen when customers enter invalid data or when you initialize Drop-in incorrectly.

3. [`onPaymentMethodReceived`](https://developers.braintreepayments.com/javascript+node/guides/drop-in#onpaymentmethodreceived), which is called on a successful tokenization of a payment method.

In Drop-in, `onPaymentMethodReceived` is only called when its parent form is submitted; we do this so that you don't have to juggle nonces. At this time, we do not provide more advanced hooks in order to keep Drop-in as simple as possible.

Hopefully, you can use these a combination of these three callbacks to provide the experience you're looking for!

**Comment by HiroAgustin** [comment]
How about when using the `customer_id` attribute to display the customer's payment methods: when the user chooses to change the payment method (either to an existing or creating a new one) no event is triggered. Shouldn't `onPaymentMethodReceived` be called so I could get the new `nonce`?

**Comment by kyledetella** [comment]
@HiroAgustin as @EvanHahn mentioned, `onPaymentMethodReceived` is only called when the form is submitted. So unfortunately, the only way to get the new `nonce` is to submit the form.

Tying nonce retrieval to only form submit events is an aspect of Drop-in (and `braintree.js` in general) that we are aware causes some confusion and can use some improvement. We are considering ways to improve these semantics and feedback like yours helps validate our decisions.

**Comment by Streemo** [comment]
+1 for an onChange and onNewCardAdded callback...

**Comment by EvanHahn** [comment]
Thanks for this feedback. We currently have no plans to make such a change, but we'll consider designs for finer grained event hooks in a future version.
