### ISSUE TITLE
How do I specify the amount?

### ISSUE THREAD

**Issue by benjaminsuch** [braintree/braintree-web#373]
I'm sorry if this is a stupid question, but what is the correct way to get the amount of a user for my transaction?

I initially thought that I would provide an input field where a user can enter his value (like in the braintree_express_example) but in the code of the braintree_express_example there is a comment which says:

`var amount = req.body.amount; // In production you should not take amounts directly from clients`

So I'm a bit lost on that. How should I tell my server how much a user wants to transfer? There is no information in the docs, likes it's obvious, so I assume I overlooked something?

So currently my code is working, but it's pretty much useless without the user being able to specify the amount.

**Comment by benjaminsuch** [comment]
Well I haven't thought about the case where the user selects items and submit his shopping cart to the server. Maybe thats the reason why it's adviced to not submit custom amounts to the server? That would make sense to me, but in my case people don't have a shopping cart or items to buy. It's more like PokerStars where people can submit "any" amount they want and that amount will credited to his account.

**Comment by Epreuve** [comment]
Hey @benjaminsuch.  You're correct in that typically when selling something, you wouldn't want to simply pass and use the amount from the client side (especially not without validation), as it would open up the ability for a clever actor to change the amount.  This is where our recommendation comes from.

However, in your case as this would be an intentional feature, that suggestion wouldn't apply.  Similar cases where that might not apply would be when taking donations, as you'd like to allow the customer to set the amount being donated.

Of course, you'll still want to follow best practices, sanitize any input coming from the client side, and validate the amount is a real number prior to attempting your transaction, but otherwise taking a value from the client side is a valid use case, just not a typical one.
