### ISSUE TITLE
'crypto' error from requirejs

### ISSUE THREAD

**Issue by zaharafirespotter** [braintree/braintree-web#390]
### General information

* SDK version: 3.37.0
* Environment: Sandbox
* Browser and OS: Chrome 69.0.3497.100 (Official Build) (64-bit) on MacOS 10.11.6
* Backbone: 1.0.0

### Issue description

I added Advanced Fraud Tools to our current braintree integration by requiring only client.min.js and data-collector.min.js, but I get the following console log error.

![screen shot 2018-09-24 at 1 11 29 pm](https://user-images.githubusercontent.com/12174613/45976365-6c54e680-bffb-11e8-97ad-570a86257207.png)

The integration works, I can get device-data, send it to the server-side lib, and decline the test fraud credit card. The only issue is the js error. I followed the instructions below from https://developers.braintreepayments.com/guides/client-sdk/setup/javascript/v3#amd-(using-require.js).

![screen shot 2018-09-24 at 1 00 08 pm](https://user-images.githubusercontent.com/12174613/45975761-d79db900-bff9-11e8-899b-838e131fe876.png)

**Comment by crookedneighbor** [comment]
I think this is very closely related to https://github.com/braintree/braintree-web/issues/386

**Comment by zaharafirespotter** [comment]
@crookedneighbor, does this mean the js 'crypto' error is out of my hands because of sjcl?

**Comment by crookedneighbor** [comment]
No, I think there's something we can do about it. 

I _think_ the problem is that sjcl prefers crypto if it is available and falls back to a browser polyfill if not. Our build process sees that crypto is required and shims it, so the built file includes both sjcl's polyfill and a shim for crypto. Which makes it very large.

Your build process _does not_ shim it, so it's attempting to use it, but it can't and falls back to the web polyfill provided by sjcl.

So I think if we're able to configure it to not use crypto at all, #386 will be solved and this issue will be solved as well.

For now, if you're able to generate device data and send it to your sever, I wouldn't worry about the warning in the console.

**Comment by crookedneighbor** [comment]
I'm not receiving that error. Here's my code:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>title</title>
  </head>
  <body>

    <script
  data-main="main.js"
  src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.1/require.min.js"
  ></script>
  <script src="/main.js">
  </script>
  </body>
</html>
```

```js
// main.js
require.config({
  paths: {
    braintreeClient: 'https://js.braintreegateway.com/web/3.38.0/js/client.min',
    dataCollector: 'https://js.braintreegateway.com/web/3.38.0/js/data-collector.min'
  }
});

require(['braintreeClient', 'dataCollector'], function (client, dataCollector) {
  client.create({
    authorization: 'sandbox_f252zhq7_hh4cpc39zq4rgjcg'
  }, function (err, clientInstance) {
    dataCollector.create({
      kount: true,
      client: clientInstance
    }, function (err, dc) {
      console.log(dc); // device data here
    });
  });
});
```

Are you doing anything special to trigger that error?

**Comment by crookedneighbor** [comment]
Haven't heard from you in a week, so I assume you've figured out the issue with your setup and I'm going to close this.
