### ISSUE TITLE
Browser doesn't suggest save credit card and autofill

### ISSUE THREAD

**Issue by Ilchuk-Mihail** [braintree/braintree-web#418]
### General information

* SDK version: 3.40.0 
* Environment: Sandbox and Production 
* Browser and OS:  Last versions Opera 58.0.3135.79 and Chrome (64-bit)  on Windows 10

### Issue description

I loaded this scripts for create payment. 
Also I implemented getting nonce, process payment in angular (1.6) directive. 
```
    <!-- Load the client component. -->
    <script src="https://js.braintreegateway.com/web/3.40.0/js/client.min.js" async></script>

    <!-- Load the PayPal component. -->
    <script src="https://js.braintreegateway.com/web/3.40.0/js/paypal.min.js" async></script>

    <!-- Load Hosted Fields component. -->
    <script src="https://js.braintreegateway.com/web/3.40.0/js/hosted-fields.min.js" async></script>
```

But when I write credit card information, browser doesn't suggest autofill card information and then doesn't suggest save credit card.  
How to allow browser to save credit card? 

I saw older issuee with similar problems, I read alll, and try to upgrade version but it still doesn't work.

**Comment by crookedneighbor** [comment]
What browser are you having issues with? I'm not having any trouble with Chrome or Safari.

**Comment by Ilchuk-Mihail** [comment]
Browser and OS: 
Last versions Opera 58.0.3135.79 and Chrome (64-bit) on Windows 10

I tested it in Chrome and Opera.

**Comment by crookedneighbor** [comment]
Just tested in both Chrome and Opera on Windows 8. No issues. Will try to download a Windows 10 VM later today.

Do you have any saved payment methods on your browser? If you have none, I wouldn't expect the credit card menu to appear.

![cc autofill](https://user-images.githubusercontent.com/2916945/53813728-ed59c780-3f23-11e9-84e3-75ed6783b270.gif)

**Comment by Ilchuk-Mihail** [comment]
@crookedneighbor 
I don't have saved payment methods. But it also doesn't allow me to save it.

**Update:**
I added payment method manually in chrome settings. 
And then form suggests autofill payment method.
So autofill works correctly. I guess. 
But, but the issue "Browser doesn't suggest save credit card"  is still there.


So, when I write credit card info, I expect the browser suggest me to save this payment method, but it doesn't.

**Comment by crookedneighbor** [comment]
This is trickier to handle then you'd think. The save card prompt is only shown when a form actually gets submitted, and since the credit card inputs are protected inside the Braintree iframes, they can't be picked up by your form submission. 

We do some extra work with additional hidden inputs inside the credit card number frame to facilitate accepting existing credit cards: https://github.com/braintree/braintree-web/blob/86a6ac4121f0f91b8ebeabfd77e47b5f6403af51/src/hosted-fields/internal/index.js#L100-L122

We _may_ be able to do something like this to capture new cards, if this stack overflow answer is correct: https://stackoverflow.com/a/29885896

But since we're juggling multiple iframes and would need to trigger the dummy form submission programmatically when tokenization is requested, it may just not be possible.

This is not a super high priority, as it works already with previously saved cards, but we'll keep this open while we investigate a solution.

**Comment by crookedneighbor** [comment]
I finally got a chance to dig into the proposed solution in the stackoverflow post, but it resulted in Safari declaring that the form submission would be insecure when pointed to an iframe on the page, so I don't think this will be possible at this time. 

Going to close this since there seems to be no way to simulate the prompt to add the card without also breaking the customer flow.
