### ISSUE TITLE
Postal code validation does not work

### ISSUE THREAD

**Issue by vill** [braintree/braintree-web#425]
Hi there.

### General information

* SDK version: 3.44.2
* Environment: Sandbox
* Browser and OS: Opera 49.0.2725.64 on Mac OS X 10.9.5 64-bit

### Issue description

When using a wrong [postal code](https://braintree.github.io/braintree-web/current/module-braintree-web_hosted-fields.html#~fieldOptions) with [Hosted Fields](https://github.com/braintree/braintree-web#hosted-fields-integration), for example:
```
Card Number: 4111111111111111
CVV: 000
Expiration Date: 12/20
Postal Code: 1111111111
```
`braintree-web` does not find errors and returns `nonce`, but [when using](https://developers.braintreepayments.com/reference/request/customer/create/ruby) this `nonce` an error occurs on the server:

```ruby
::Braintree::Customer.create(
  payment_method_nonce: nonce,
  credit_card: {
    options: {
      make_default: true,
      verification_merchant_account_id: merchant_account_id,
      verify_card: true
    }
  }
)

=> #<Braintree::ErrorResult params:{...} errors:<customer/credit_card/billing_address:[(81809) Postal code may contain no more than 9 letter or number characters.]>>
```
How can I validate the postal code on the client?

**Comment by crookedneighbor** [comment]
If you'd like to catch these errors on the client, you can vault on the client by generating a client token with a customer id (plus the other options you specified). https://developers.braintreepayments.com/reference/request/client-token/generate/ruby#customer_id

Then, when tokenizing with hosted fields, simply add `vault: true` as an option:

```
hostedFieldsInstance.tokenize({vault: true}, function (err, payload) {
  if (err) {
    // handle error
    return;
  }

  payload.nonce // token representing the vaulted card
});
```

Note: as [reported in this issue](https://github.com/braintree/braintree-web/issues/415), an unmatched postal code will pass back an error with the code `HOSTED_FIELDS_TOKENIZATION_CVV_VERIFICATION_FAILED`. We can't rename it to something like `HOSTED_FIELDS_TOKENIZATION_FRAUD_TOOLS_VERIFICATION_FAILED` until we publish a new major version, because it would break backwards compatibility. So just be aware if you're trying to catch specific error codes.
