### ISSUE TITLE
Hosted Fields postal code autofill doesn't work when other non-hosted fields are used

### ISSUE THREAD

**Issue by barrett-vegas-com** [braintree/braintree-web#448]
### General information

* SDK version: 3.50.0
* Environment: Sandbox and Production
* Browser and OS: Chrome 76.0.3809.100 (64-bit) on MacOS 10.14.6 (likely others as well)

### Issue description

When using non-hosted fields for something like a full name and e-mail address alongside a postal code hosted field, the browser will prompt for autofill when entering the name or e-mail field and will autofill both of those properly. The postal code does not get autofilled, however if one clicks inside the field then one is given the option to autofill with the stored postal code.

Note that an address needs to be saved in the Chrome autofill settings to properly test this. Here is a quick modification of the codepen example which exhibits the issue:
https://codepen.io/barrett-vegas-com/pen/ZEzLVZz

Click in the name field, choose to autofill, notice that name and email are filled in, but not postal code.

**Comment by crookedneighbor** [comment]
This is pretty much impossible to make work, since the inputs inside the iframes can't receive the autofill information from the browser when it originates from an input outside those iframes.

An easy workaround for this is to not collect the postal code via hosted fields at all, just make it a regular input element and include it as part of the billing address object when tokenizing: https://braintree.github.io/braintree-web/current/HostedFields.html#tokenize

Codepen: https://codepen.io/braintree/pen/dybRvGr
