### ISSUE TITLE
three-d-secure https validation 

### ISSUE THREAD

**Issue by kpiotr** [braintree/braintree-web#454]
### General information

* SDK version: 3.52.0
* Environment prod
* Browser and OS cordova

### Issue description
We've run into problem with this particular line while integrating 3ds2 into our payments flow https://github.com/braintree/braintree-web/blob/ffe488630cbb33974c43971d023be25583e23c48/src/three-d-secure/index.js#L58 
It works well on web and staging environments but there is a catch. We use cordova to deliver our mobile apps. It turns out that cordova uses different protocol to `https` to serve the webview, so simple `location.protocol === 'https'` check is failing.

While I realize that `braintree-web` doesn't support cordova officially, there are a couple issues here:
1. `isProduction` check extends the feedback loop dramatically 
2. Shouldn't the call to tokenization/3ds fail anyway if made over http?
3. Can this be reduced to a warning that is displayed both on staging and prod?

As a quick, dirty fix we ended up forking and removing the `isHttps` check. We would like to get rid of the fork though.

**Comment by hollabaq86** [comment]
👋 @kpiotr, thanks for reaching out. If you need to use this component for your app, forking our library to make the changes you need is the best approach.

We need to include checks such as `isProduction && !isHTTPS()` because they're requirements for merchants using braintree-web on the web. As stated in our [reference docs](https://braintree.github.io/braintree-web/current/#browser-support-webviews), we do not test or develop our JS SDK for hybrid runtimes such as Cordova, PhoneGap, Ionic, React Native, and Electron.

**Comment by crookedneighbor** [comment]
^ specifically, it's a requirement for using the 3ds component in production on the web.
