### ISSUE TITLE
do you have tokenizePayPalAccount example?

### ISSUE THREAD

**Issue by villav** [braintree/braintree-web#46]

**Comment by goggin13** [comment]
Hi @villav!  I'm on the Pay with PayPal team at Braintree.  Unlike the `tokenizeCreditCard` function, the tokenizePayPalAccount function won't be much use outside of a Braintree integration.  

We use it internally to store the data that comes back from the [popup](https://developers.braintreepayments.com/javascript+ruby/guides/paypal/checkout-with-paypal), which then allows you to vault or process a transaction.

However, as a consumer of the Braintree APIs, you will never need to invoke this method directly.  Instead, the Braintree PayPal integrations will show the user a popup, do the authentication with PayPal and return you a `paymentMethodNonce` for use with the Braintree API.

**Comment by villav** [comment]
I was just looking a way to pass shipping address and amount right before click that invoke popup similar to tokenizeCreditCard

**Comment by sornon1** [comment]
@villav I think you're looking for the options in the [PayPal Checkout configuration](https://developers.braintreepayments.com/javascript/guides/paypal/checkout-with-paypal#shipping-addresses)

**Comment by schneiderik** [comment]
Hi @villav, I'm also on the Pay with PayPal team at Braintree. At this time, merchants can only configure their PayPal checkout when `braintree.setup` is called.  It is not possible to setup your Braintree client-side integration on page load, and then pass additional configuration data to it just before the PayPal popup is opened by the user. It is also not recommended to invoke `braintree.setup` multiple times on a single page.

One possible solution to this problem is to have the desired amount and shipping address set on a previous step of your checkout process. You may then proceed to a checkout page where `braintree.setup` is invoked with the shipping address and amount from the previous step.

For more information on the PayPal checkout configuration, the guide @sornon1 posted should contain everything you need to get setup.

**Comment by villav** [comment]
Thanks.
