### ISSUE TITLE
venmoIstance.tokenize doesn't open venmo app, promise never resolves

### ISSUE THREAD

**Issue by Force72** [braintree/braintree-web#482]
### General information

* SDK version: JavaScript v3
* Environment: Sandbox
* Browser and OS: cordova webview on iOS 13.1.3

### Issue description

I'm trying to implement a custom integration of Braintree Venmo on cordova. After initializing the Braintree client and venmo instances, I call on venmoInstance.tokenize via a button press, but the promise it returns never resolves, throws an error, or timesout. It's my understanding that the call to tokenize should open the Venmo app on my phone, which it never does. Looking at the source for tokenize in braintree-web/venmo/venmo.js, it appears that the code starting at line 155 to open the venmo app isn't working for a cordova webview. Therefore the visiblityChangeListener that gets set right after that never fires, and the promise never resolves. I was wondering if there might be some way to overwrite the global variable so that this functionality could work on cordova. Here's some code to reproduce in issue. It's taken pretty much straight from the Braintree documentation.

```
import braintreeClient from 'braintree-web/client';
import braintreeVenmo from 'braintree-web/venmo';

let venmoButton = document.getElementById('venmo-button');

braintreeClient.create({
	authorization: 'my_sandbox_tokenization_key'
}).then((clientInstance) => {

	braintreeVenmo.create({
		client: clientInstance,
		allowNewBrowserTab: false
	}).then((venmoInstance) => {

		// Verify browser support before proceeding.
		if (!venmoInstance.isBrowserSupported()) {
			console.log('Browser does not support Venmo');
			return;
		}

		displayVenmoButton(venmoInstance);
	})

}).catch((err) => {
	console.log('ERROR: ', err);
});

function displayVenmoButton(venmoInstance) {
	venmoButton.style.display = 'block';

	venmoButton.addEventListener('click', () => {
		venmoButton.disabled = true;

		// It gets here
		console.log('Before tokenize');

		venmoInstance.tokenize().then((payload) => {
			// It never gets here
			console.log('payload: ', payload);
		}).catch(err => {
			// It never gets here
			console.log('error: ', err)
		});
	});
}
```

**Comment by Force72** [comment]
Hey,

Just double checking to see if anyone has received this.

**Comment by crookedneighbor** [comment]
Sorry for the delay. Cordova is not an officially supported platform for the web SDK. 
See [`WEBVIEWS AND HYBRID ENVIRONMENTS` section](https://braintree.github.io/braintree-web/current/)

However, my best guess is that this is just the normal trouble that the venmo component has within a webview, since it's unable to return to the correct location.

You can try using the [`deepLinkReturnUrl` create attribute](https://braintree.github.io/braintree-web/current/module-braintree-web_venmo.html#.create), which is designed to allow venmo to work within a webview on iOS.

It should _just work_, but there may be other complications because of the Cordova environment.

**Comment by Force72** [comment]
Thank you! I've been able to finagle it into working.

**Comment by sandy1198** [comment]
@Force72  
I bro kindly share the last solution code , how you use deep linking I'm working on ionic cordova any help to popup the venmo app
