### ISSUE TITLE
Input field within hosted fields iframe has font size inherit from iframe, but ...

### ISSUE THREAD

**Issue by ming222555** [braintree/braintree-web#483]
### General information
* SDK version: 3.0.0
* Environment: Sandbox, Production
* Browser and OS: Chrome 56.0.2924.87 (64-bit) on Windows

### Issue description
Hi all,
it seems that for an input field ( e.g. card number) within hosted fields iframe, its font size inherits from the iframe's body, while a developer defined label ( whose css customizable by developer's stylesheet) for same input inherits from root window itself. This mismatch of source-of-font-size-inheritance is unsuitable for responsive design. As such, shouldn't braintree let font size of iframe's input field be tied to root window instead? If not, then perhaps how about providing a means to control font-size and positioning of a label within input field's iframe?
... rgds, newbie

**Comment by crookedneighbor** [comment]
Hi @ming222555. Due to the nature of iframes, we can't retrieve the properties from the parent window, so this can't be done automatically by the SDK.

I assume you're using @media queries in your CSS to change your font size dynamically? This also won't work in the iframes, because the screen size will be relative to the iframe instead of to the parent page.

However, you can emulate this behavior using the window.resize event and the `addClass`/`removeClass` methods on the hosted fields instance. Here's a codepen: https://codepen.io/braintree/pen/GRgWXWK

It sets the font-size of inputs to be 3em by default, but shrinks them to 1.5em when the screen width is 800px or lower.

**Comment by ming222555** [comment]
Hi Blade a.k.a. crookedneighbor,
tks for ur prompt reply... i neither know or am aware that "Due to the nature of iframes, and so cannot retrieve the properties from the parent window". But now that i do, i really appreciate for pointing out this to me... seems that i should read up more on iframes...
Also tks for the codepen lnk you provided, which i will go take a look later ...
Best rgds, ming222555

**Comment by ming222555** [comment]
Hi, it's me again... earlier u mentioned that "using @media queries in your CSS to change your font size dynamically... won't work in the iframes, because the screen size will be relative to the iframe instead of to the parent page". I now have an idea... why not allow some configuration ( including media query) for iframe-html-fontsize inside the javascript? since such configuration already applies to input-font-size... something like in the example below ...
================
braintree.hostedFields.create({
            client: clientInstance,
            styles: {
                'input': { 'font-size': '.8125rem;' },
                    '@media only screen': { 'html': { 'font-size': '80%' }, 'input': { 'font-size': '.8125rem;' }},
                    '@media only screen and (min-width: 56.25em)': { 'html': { 'font-size': '90%' }, 'input': { 'font-size': '.8125rem;' }},
                    '@media only screen and (min-width: 75em)': { 'html': { 'font-size': '100%' }, 'input': { 'font-size': '.8125rem;' }},
                    '@media only screen and (min-width: 112.5em)': { 'html': { 'font-size': '120%' }, 'input': { 'font-size': '.8125rem;' }},...
================
... of which @media query in above example i will also duplicate to my main css as well i.e.. parent window so that both iframe and parent obey same set of media queries, but only if iframe-html-fontsize is configurable ...

**Comment by crookedneighbor** [comment]
The iframe calculation would be dependent on the size of the iframe's calculation of the screen size, so this only works if your iframe's width is 100% of the parent window. You get wonky behavior when trying to do these kinds of media queries when it is any less than 100%. 

Because the same effect is able to be accomplished with a little JavaScript (see the codepen), it's not something we're going to explore right now.

**Comment by crookedneighbor** [comment]
(also, I edited your comment to use a code snippet so it was easier to read)
