### ISSUE TITLE
Web component support?

### ISSUE THREAD

**Issue by jdalton** [braintree/braintree-web#495]
I've had devs report issues with document query methods (`querySelector` and `querySelectorAll`) when embedding braintree inside a web component. Is their guidance or support for embedding braintree in web components?

**Comment by crookedneighbor** [comment]
Sorry for the late reply on this. We're working on having official support for this. The tricky thing is that currently the hosted fields frames need to find each other by looping over the frames on the parent window, but when nested inside a web component, they lose access to the frames array on the parent window.

**Comment by crookedneighbor** [comment]
I have a working beta just about ready to go. @jdalton would you be interested in giving it a try? Want to make sure it satisfies a real world use case before releasing it officially.

**Comment by crookedneighbor** [comment]
If anyone is interested in trying a beta release that adds official support for the shadow DOM, you can try it out here:

https://js.braintreegateway.com/web/3.64.0-beta.1/js/client.min.js
https://js.braintreegateway.com/web/3.64.0-beta.1/js/hosted-fields.min.js

The fix was to check if the container being passed existed in the shadow DOM, and if it does, add `slot` elements into the container and the iframes in divs referencing those slots on the main page. This allows the iframes to communicate with each other even when inside the shadow DOM.

**Comment by crookedneighbor** [comment]
3.64.1 includes support for web components.
