### ISSUE TITLE
braintree 在微信小程序中不可用

### ISSUE THREAD

**Issue by liugangFrancis** [braintree/braintree-web#502]
### General information

* SDK version: 3.0.0 
* Environment: Sandbox or Production
* Browser and OS : iphone 6s , wechat mini 开发者工具

 "braintree-web": "^3.62.2",
    "braintree-web-drop-in": "^1.22.1",

module "miniprogram_npm/braintree-web-drop-in/braintree-web/client" is not defined
Error: module "miniprogram_npm/braintree-web-drop-in/braintree-web/client" is not defined

**Comment by crookedneighbor** [comment]
The wechat platform is not officially supported by Braintree. Please contact Braintree support for help with your integration. It may turn out that you can leverage the GraphQL API directly instead of using the client sdks that are built exclusively for the web browser environment.

https://help.braintreepayments.com/
