### ISSUE TITLE
data-collector "paypal" option is not honoured

### ISSUE THREAD

**Issue by Jokero** [braintree/braintree-web#509]
### General information

* SDK version: 3.62.0
* Environment: Production
* Browser and OS: Chrome 83.0.4103.116 (64-bit) on MacOS 10.15.4

### Issue description

According to CSP section of the page https://braintree.github.io/braintree-web/current/ we need just to set basic CSP directives to make `braintree-web` work in case of not using specific components (paypal, google, etc.):
![image](https://user-images.githubusercontent.com/434135/86588286-17961c00-bf94-11ea-980e-fdba0b49986f.png)

However after applying these directives we have the following error in the browser console:
```
Refused to load the script 'https://c.paypal.com/da/r/fb.js' because it violates the following Content Security Policy
```
The request is blocked as it violates CSP although you do not require to allow requests for that domain in the documentation.

After checking `braintree-web` code I found that `data-collector` uses `fraudnet` module which tries to load that paypal script https://github.com/braintree/braintree-web/blob/master/src/data-collector/fraudnet.js#L38. Moreover `data-collector` accepts `paypal` option (https://github.com/braintree/braintree-web/blob/master/src/data-collector/index.js#L94) but actually does not use it in any way like it does for `kount` (https://github.com/braintree/braintree-web/blob/master/src/data-collector/index.js#L121). 

So I'd expect to have `paypal` option check for `fraudnet` here https://github.com/braintree/braintree-web/blob/master/src/data-collector/index.js#L143

**Comment by crookedneighbor** [comment]
👋  Thanks for the callout. The Data Collector docs have been updated to include the required PayPal urls: https://braintree.github.io/braintree-web/current/#content-security-policy

**Comment by Jokero** [comment]
@crookedneighbor Thanks for the reply. I'm still having a question what `paypal` option is used for? It's defined in documentation on the website and in jsdoc but actually is not used anywhere. It's marked as deprecated, should it be removed?

**Comment by crookedneighbor** [comment]
To be clear, previously, you'd only specify `paypal: true` when you wanted to use PayPal's fraud detection. Now, that same underlying fraud detection is used for PayPal as well as credit cards, so creating the data collector component at all sets up the PayPal scripts. Because of that, the `paypal` option no longer needs to be set to get that when creating a data collector component.

In the next major version, the `paypal` option will be dropped from the docs.

The content security section of the data collector docs should always have included those PayPal urls. We just missed it because the `paypal` option previously only applied to PayPal integrations, so it was covered under the PayPal section. Now the same data collection applies to credit cards as well, so we've clarified the docs to include it in the data collector section (which, it should have been there all along).
