### ISSUE TITLE
Extra events history are added when 3D Secure form is loaded and sumbitted

### ISSUE THREAD

**Issue by andrei-oksentyk** [braintree/braintree-web#512]
### General information

* SDK version: 3.63.0
* Environment: Sandbox
* Browser and OS: Windows10/Chrome 84, Android/Chrome 84, Linux(Manjaro 19)/Chrome 84

### Issue description
Hi! We are using Braintree with 3D Secure veruvication and we faced the issue with extra events which push to history while 3D Secure loading and submiting. On screeshot below you can see 3 states of history:
1. User comes to payment page, fill details and ready to submit
2. 3D Secure verification is loaded
3. User submit 3D Secure form
![image](https://user-images.githubusercontent.com/38737282/88659979-976c5d80-d0de-11ea-8b5e-7acfc728e7d2.png)

The issue is that when payment proccess failed or user close modal and try to return to previous page by clicking on "go back" browser button, he comes to the same page. It require to click several times to go back to destination page.
Additionaly we tested the issue on devices/browsers:  Linux/Firefox78, iPhone11/Safari@12.1, Windows10/Edge11. There are no issues with them.

**Comment by crookedneighbor** [comment]
This occurs because there are redirects happening inside the 3ds iframe. You can see the same thing happening in this example that redirects between a few iframes

![iframes](https://user-images.githubusercontent.com/2916945/88670050-3a56b480-d0aa-11ea-8a83-fa4a82ccc6ab.gif)

To be honest, was surprised to learn that redirects in iframes affect the history of the parent page/browser.

I'll do some investigation and see if there's anything we can do in the Braintree SDK to mitigate this, but I suspect some of these are going to be occurring at the bank page level, so we don't have any control over them.

**Comment by crookedneighbor** [comment]
Verified that there's nothing we can do at the Braintree SDK level. I've contacted our MPI provider to see if there is anything they can adjust to avoid this. Hopefully they can swap out a few `location.href =` calls with `location.replace` and be done with it, but I suspect that the underlying bank pages may add additional events.

Going to close this now, as there is nothing actionable for Braintree to do, but will update here if our MPI provider has a better solution.
