### ISSUE TITLE
Handler Function Is Never Hit In initializeChallengeWithLookupResponse API

### ISSUE THREAD

**Issue by AudreyMeng** [braintree/braintree-web#519]
### General information

* SDK version: 3.57.0
* Environment: Production
* Browser and OS: Chrome 84.0.4147.125 (64-bit) on MacOS 10.15.6 -->

### Issue description
We are trying to customize iframe generated by `initializeChallengeWithLookupResponse` API
```
braintree.client
.create({ authorization: braintreeClientToken })
.then((newBraintreeClient) => {
  braintree.threeDSecure
    .create({
      client: newBraintreeClient,
      version: '2-inline-iframe',
      loggingEnabled: true,
    })
    .then((newThreeDSecureClient) => {
      newThreeDSecureClient.on(
        'authentication-iframe-available',
        (payload, next) => {
          console.log(JSON.stringify(payload));
          next();
        },
      );
      newThreeDSecureClient
        .initializeChallengeWithLookupResponse(lookupResponse)
        .then((payload, error) => {
          // ...
        })
        .catch((error) => {
          // ...
        });
    });
})
```
But the handler function in newThreeDSecureClient.on('authentication-iframe-available', **handler**) is never triggered even though we can find authentication-iframe-available in events inside initializeChallengeWithLookupResponse. We never hit `console.log(JSON.stringify(payload));`.
Is this a bug or the way we are using the APIs needs modification?

**Comment by gesa** [comment]
hey @AudreyMeng is it possible you're seeing output to the console, just not the output you expected? The callback parameters for the [authentication-iframe-available event](https://braintree.github.io/braintree-web/current/ThreeDSecure.html#event:authentication-iframe-available) are `event, next`, there is no ThreeDS payload that gets passed at that time.

I tried a recreation of your code and I encountered an error due to the fact that the iframe is never presented to the user. idk if that's just an oversight due to the fact that you were offering a slimmed down example for us (which, thank you!) but once I ran a transaction appending the iframe to the DOM, it logged out a near-empty object (`{"element":{}}`), which is what I would have expected to see in that scenario.

**Comment by AudreyMeng** [comment]
I opened dev-tools to debug, `console.log(JSON.stringify(payload));` is never hit.
iframe shows up in my env which `initializeChallengeWithLookupResponse` API provides.

My goal is trying to customize the iframe provided by `initializeChallengeWithLookupResponse` like adding new title. Could you help to share the right way to do that?

**Comment by crookedneighbor** [comment]
Can you provide a staging site which demonstrates the issue? I'm not having any issues with it on my end.

**Comment by crookedneighbor** [comment]
Can you also provide how you're creating the lookup response? It could be that something is going wrong there, and no acs url is available.

**Comment by AudreyMeng** [comment]
> Can you also provide how you're creating the lookup response? It could be that something is going wrong there, and no acs url is available.

Lookup response is from server side. I looked in the response, it includes non-empty acs URL. The step up renders fine, but the authentication-iframe-available event handler is not getting hit.

For staging site, I will send private email to you (since it's confidential info).

**Comment by crookedneighbor** [comment]
Either open a support ticket at https://help.braintreepayments.com/ or reach out to your Braintree account manager. Be sure to reference this issue.

**Comment by crookedneighbor** [comment]
Was able to go through your staging site. Looks like you created 2 three d secure instances, one using `version: '2'` and one using `version: '2-inline-iframe'`. Since `version: '2'` was created first, the global Cardinal object was configured to use the normal Cardinal modal, and the second call to configure the Cardinal SDK was ignored. (not by Braintree, it's ignord by the Cardinal SDK).

You can fix this problem by either using a single 3D Secure instance or by instantiating both with `version: '2-inline-iframe'`.
