### ISSUE TITLE
Hosted Fields card number/expiry date formatting on Samsung Internet browser

### ISSUE THREAD

**Issue by dimpey** [braintree/braintree-web#528]
### General information

* SDK version: 3.66.0
* Environment: Sandbox and Production
* Browser and OS: Samsung Internet 12.1.4.3 on Samsung Galaxy A50 Android 10

### Issue description

Hosted Fields automatic formatting of the card number and expiry date fields isn't working on Samsung Internet browser.  No spaces are added in the card number and leading zero/forward slash is not added to the expiry date field.
![Screenshot_20201020-153322_Samsung Internet](https://user-images.githubusercontent.com/5920911/96540721-2a85ef80-12ea-11eb-9fc7-584eefe5cdf4.jpg)

**Comment by crookedneighbor** [comment]
This is expected for the Samsung browser. It implements non-standard behavior for keyboard events, and we found early on that people using samsung browsers were unable to input their credit card details at all.

We deemed it better to _not_ do input formatting for samsung browsers, rather than prevent the customer from entering their credit card details at all.
