### ISSUE TITLE
Documentation/Guide for integrating Plaid?

### ISSUE THREAD

**Issue by acomito** [braintree/braintree-web#537]
I see Plaid mentioned in a few places throughout the docs, such as here:

https://developers.braintreepayments.com/guides/ach/overview#tokenizing

But I don't see any guide for exactly how it's integrated. Is there one?

**Comment by crookedneighbor** [comment]
I think you're looking for this: https://articles.braintreepayments.com/guides/payment-methods/ach#tokenized-check

tl;dnr, sign up for your own plaid account and add the api keys in your Braintree control panel.

The `tokenize` call is done using `bankLogin` instead of `bankDetails` and it calls the Plaid sdk under the hood. See https://developers.braintreepayments.com/guides/ach/client-side/javascript/v3#using-tokenized-check

**Comment by acomito** [comment]
Alright gotcha. I wasn't clear if we use plaid then pass in their public/access token or if we use plaid via braintree. Sounds like it's the latter. 

Thanks @crookedneighbor
