### ISSUE TITLE
Request: Expose PaymentMethod.token for vaulted paymentMethods

### ISSUE THREAD

**Issue by crackedeggs1** [braintree/braintree-web#561]
When using the PHP SDK, I currently use a PaymentMethod object's "token" attribute to associate the method with records in my database. However, when using the Javascript SDK, vaulted payment methods do not have the "token" attribute present. The only apparently unique attribute seems to be a one-time-use nonce, which I'm not sure there is a way to use to get the token -- waiting on a response from support on that.

If the Javascript SDK did expose the token, I could ensure that any changes made using the Javascript SDK were reflected in my database records.

**Comment by crookedneighbor** [comment]
If you use https://developers.braintreepayments.com/reference/request/payment-method/create/php on a Payment Method Nonce that refers to an already vaulted payment method, it will return to you the already vaulted payment method.

We intentionally don't expose the vault token on the client, because it does not expire, unlike the payment method nonce, which as you've said, is single use.

**Comment by crackedeggs1** [comment]
Thanks, that worked!

The suggestion by support had not worked (they suggested Payment Method Nonce Find, but that response object does not include token -- maybe it should).

Your suggestion works, but is contrary to my expectations reading the Payment Method Create docs. My expectation was that using create again would have generated a separate but duplicate record with a different token. Perhaps the docs should clarify this use case. It seems to me that wanting to know which payment method in the local database corresponds to the payment method returned by the Javascript SDK would be a common problem.
