### ISSUE TITLE
How to make ExpirationDate accepts **MM/YY** only (hopefully `maxLength: 5`)

### ISSUE THREAD

**Issue by primedev22** [braintree/braintree-web#579]
### General information

* SDK version: 3.0.0
* Environment: Any
* Browser and OS Any

### Issue description

Currently, ExpirationDate accepts both **MM/YY** and **MM/YYYY** formats in hosted fields. But we are in need of enabling one format only (**MM/YY** or **MM/YYYY**). Is there any option to disable one type of format?

**Comment by crookedneighbor** [comment]
Can you explain your use case about why you need to accept only a single format?

**Comment by primedev22** [comment]
First of all, thanks for your reply. :)
Now we are going to implement auto-tab between braintree hosted fields in terms of better user experience perspective.
For example;
1. User types CC: 4111 1111 1111 1111
2. system detects end of credit card and goes to expiration date
3. User types Exp: 11/25
4. We are not able to tab if we can’t limit it to just two numeric values.

**Comment by crookedneighbor** [comment]
Can't you just detect the validity of the expiration date before going forward? If a customer inputs `12/20` when they intend to put `12/2025`, it should never show up as valid. (because now that we're in the year 2021, there's no case where `12/20` would be a valid expiration date, unlike last year in 2020, where `12/20` _was_ a valid expiration date).

We won't have this ambiguity again until we get expiration dates in the `2121-2129` range. 

If you restrict to a `MM/YY` format, you're going to make a customer who goes to type `11/2025` get stuck at `11/20` and then need to backspace the `0` to put in the `5`.

**Comment by primedev22** [comment]
That makes sense to me. Thanks @crookedneighbor
