### ISSUE TITLE
onPaymentMethodReceived callback not called with paypal

### ISSUE THREAD

**Issue by clupprich** [braintree/braintree-web#58]
I have the following setup for our Braintree integration:

```javascript
braintree.setup(client_token, 'custom', {
  id: 'checkout',
  paypal: {
    container: 'paypal-container',
    onPaymentMethodReceived: function(obj) {
      // this is never called
      console.log(obj);
    }
  }
});
```

When using the PayPal button, the `payment_method_nonce` is correctly inserted and updated, but the `onPaymentMethodReceived` callback is never called. It works, however, when I change the `braintree.setup` call to be `paypal` only, instead of `custom`:

```javascript
braintree.setup(client_token, 'paypal', {
  container: 'paypal-container',
  onPaymentMethodReceived: function(obj) {
    // this is called
    console.log(obj);
  }
});
```

Any idea what I'm doing wrong?

**Comment by clupprich** [comment]
I've created a small sinatra example, which can be found here: https://gist.github.com/clupprich/6def9b88fd7fa3767562. Neither the callback on the root level, nor on the paypal level are invoked.

**Comment by kyledetella** [comment]
@clupprich there are slightly different semantics for the `onPaymentMethodReceived` callback in a `custom` integration and when using a "standalone" PayPal integration. When using PayPal in isolation (declaring `paypal` as your integration type in `braintree.setup`) there is no explicit need for a form `submit` event to retrieve the nonce. However, when using a `custom` integration, there is an expectation that a credit card form will be involved and as such, the `onPaymentMethodReceived` callback is not fired until the user attempts to submit the form.

This issue has been brought up a couple times now and I completely understand the confusion because it is a seemingly broken pattern. I can however provide a workaround for the time being while we decide what the best steps are going forward.

When `v.zero` was originally introduced, PayPal integrations were documented with an `onSuccess` method. We later decided to move to a root level callback (`onPaymentMethodReceived`) to better accommodate the orchestration of multiple payment methods in a single integration (PayPal, credit cards, Coinbase, etc). However, this `onSuccess` method is still supported and could prove useful in your case as it will fire as soon as the user completed the PayPal flow and a nonce is generated. Here is how you can use it:

```javascript
braintree.setup(TOKEN, 'custom', {
  id: 'checkout',
  paypal: {
    container: 'paypal-container',
    onSuccess: function (nonce, email) {
      // This will be called as soon as the user completes the PayPal flow
      // nonce:String
      // email: String
    }
  },
  onPaymentMethodReceived: function(obj) {
  	// This will be called when the user submits the form
  }
});
```

There are some caveats with this approach. First, the signature of `onSuccess` is different from that of `onPaymentMethodReceived`. The former presents a `nonce` and `email` value as strings (it is clearly inferred that this is a PayPal nonce) whereas the latter presents a [payment method Object](https://developers.braintreepayments.com/javascript/guides/client-sdk#global-setup). The second caveat is that depending how you have architected your checkout flow, you will receive the PayPal nonce via `onSuccess` and then again upon user submission of the form via the `onPaymentMethodReceived` callback.

I will discuss this issue with our team and provide any updates that arise from that.

One solution we have talked about in the past is to fire the `onPaymentMethodReceived` callback at several points throughout the lifecycle of an integration (when the PayPal flow finishes and again on submit). The problem with this however, is that it could break backwards compatibility for those who are expecting it to only fire once.

Thank you for bringing this up. I hope this workaround helps. Let me know if you have any further questions.

**Comment by clupprich** [comment]
Hej @kyledetella! Our main problem is that we're using CC and PayPal within the same form and want to disable validation for one or the other, depending on which payment method our customer has selected (by entering CC details or logging in with PayPal).

I just gave it a first try, but the `onSuccess` callback seems to be exactly what we need. Awesome, thanks so much!

**Comment by kyledetella** [comment]
@clupprich I understand. That is a completely reasonable integration scenario and I'm glad to hear the `onSuccess` solution works.

I am going to close this issue. Feel free to continue the conversation or re-open it if you need to.

**Comment by reel** [comment]
Hello! I am really happy to have found this issue on GitHub... Been playing with hosted fields and Paypal integration. After a while searching, I got a way to watch for a possible hidden input added to the field. As I'm working with React (virtual dom), I was wondering if that was the problem. Is it possible to at least document this on the site with custom integration (or only a note?). onSuccess works great! This is an awesome lib! Good work!

**Comment by quinnjn** [comment]
@reel We don't fully understand your question, but it doesn't seem in scope with this closed issue. 

Can you send us an email (support@braintreepayments.com) or open a new issue?

**Comment by Boycce** [comment]
Thanks for this issue, `onSuccess` has helped me return user info and visual responses from a headless paypal button. However I noticed `onSuccess` is depreciated? [Ref.](https://developers.braintreepayments.com/reference/client-reference/javascript/v2/paypal#options)

**Comment by crookedneighbor** [comment]
@Boycce The documentation you linked to and [this comment by Kyle](https://github.com/braintree/braintree-web/issues/58#issuecomment-118852093) explains why it is deprecated. 

However, even though it is deprecated, it _will not_ be removed from version 2 of the braintree-web library, so it is safe to use.

**Comment by basco-johnkevin** [comment]
@kyledetella I'm experiencing a similar issue. `onPaymentMethodReceived` callback is not immediately called after paypal login flow when I'm using custom integration & supporting multiple payment methods (credit card & paypal). It is called immediately though when I'm using custom integration but only support a single payment method (paypal).

https://gist.github.com/anonymous/255702dbd196d3b5592f395b9ad60d3b

I'm now using `onSuccess` callback as a solution but I wanted to pre-populate the our form fields with the customer's paypal first name, last name, address, zip etc... Unfortunately, those infos are not available on the `onSuccess` callback. Those info are available on `onPaymentMethodReceived`. How can I fetch those details inside the onSuccess callback?

**Comment by crookedneighbor** [comment]
@basco-johnkevin You can do this with v3 of the sdk. 

Here's an example using the new [PayPal Checkout component](http://braintree.github.io/braintree-web/current/PayPalCheckout.html):

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>PayPal Autofill Form Demo (v3)</title>
    <link rel="stylesheet" type="text/css"  href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.7/semantic.min.css" />
    <style>
      .ui.container {
        margin: 50px auto;
      }

      .ui.container .segment {
        max-width: 600px;
        margin:auto;
      }
    </style>
  </head>
  <body>
    <div class="ui container">
      <h1>PayPal Autofill Form Demo (v3)</h1>
      <div class="ui form segment">
        <div id="paypal-button"></div>
        <div class="field">
          <label>First Name<label>
          <input id="first-name" />
        </div>
        <div class="field">
          <label>Last Name<label>
          <input id="last-name" />
        </div>
        <div class="field">
          <label>Email<label>
          <input id="email" />
        </div>
      </div>
    </div>

    <!-- creates the braintree object on the window -->
    <script src="https://js.braintreegateway.com/web/3.8.0/js/client.min.js"></script>
    <script src="https://js.braintreegateway.com/web/3.8.0/js/paypal-checkout.min.js"></script>
    <!-- creates the paypal object on the window and manages UI for PayPal login -->
    <script src="https://www.paypalobjects.com/api/checkout.js"></script>
    <script>
      // fill in with your own client token or tokenization key
      var auth =  'eyJ2ZXJzaW9uIjoyLCJhdXRob3JpemF0aW9uRmluZ2VycHJpbnQiOiJhZTc3NzI1NzJmN2U4ZTQyZjVmNGU0YTQ4ZTE1YTg0NTA2Y2MyY2VkMzUxOTNjOTMwYTAxN2YxZDg2YTRhZThlfGNyZWF0ZWRfYXQ9MjAxNy0wMi0wOFQyMjowMzozMy40NDU3MTQxMTcrMDAwMCZtZXJjaGFudF9pZD1oaDRjcGMzOXpxNHJnamNnJnB1YmxpY19rZXk9cTNqdHNxM2QzcDJyaDV2dCIsImNvbmZpZ1VybCI6Imh0dHBzOi8vYXBpLnNhbmRib3guYnJhaW50cmVlZ2F0ZXdheS5jb206NDQzL21lcmNoYW50cy9oaDRjcGMzOXpxNHJnamNnL2NsaWVudF9hcGkvdjEvY29uZmlndXJhdGlvbiIsImNoYWxsZW5nZXMiOlsiY3Z2Il0sImVudmlyb25tZW50Ijoic2FuZGJveCIsImNsaWVudEFwaVVybCI6Imh0dHBzOi8vYXBpLnNhbmRib3guYnJhaW50cmVlZ2F0ZXdheS5jb206NDQzL21lcmNoYW50cy9oaDRjcGMzOXpxNHJnamNnL2NsaWVudF9hcGkiLCJhc3NldHNVcmwiOiJodHRwczovL2Fzc2V0cy5icmFpbnRyZWVnYXRld2F5LmNvbSIsImF1dGhVcmwiOiJodHRwczovL2F1dGgudmVubW8uc2FuZGJveC5icmFpbnRyZWVnYXRld2F5LmNvbSIsImFuYWx5dGljcyI6eyJ1cmwiOiJodHRwczovL2NsaWVudC1hbmFseXRpY3Muc2FuZGJveC5icmFpbnRyZWVnYXRld2F5LmNvbS9oaDRjcGMzOXpxNHJnamNnIn0sInRocmVlRFNlY3VyZUVuYWJsZWQiOnRydWUsInBheXBhbEVuYWJsZWQiOnRydWUsInBheXBhbCI6eyJkaXNwbGF5TmFtZSI6ImJ0IiwiY2xpZW50SWQiOiJBVlFKZjlhLWI2am1ZRmdpb05wSTJpNTdyc1FrSGpSWlp2NGQ5RFpMVFUwbkJTdWZraHdBQ0FaeGowbGR1ODVqYXNNMDJqRlJQS2FUSU5DTiIsInByaXZhY3lVcmwiOiJodHRwOi8vZXhhbXBsZS5jb20vcHAiLCJ1c2VyQWdyZWVtZW50VXJsIjoiaHR0cDovL2V4YW1wbGUuY29tL3RvcyIsImJhc2VVcmwiOiJodHRwczovL2Fzc2V0cy5icmFpbnRyZWVnYXRld2F5LmNvbSIsImFzc2V0c1VybCI6Imh0dHBzOi8vY2hlY2tvdXQucGF5cGFsLmNvbSIsImRpcmVjdEJhc2VVcmwiOm51bGwsImFsbG93SHR0cCI6dHJ1ZSwiZW52aXJvbm1lbnROb05ldHdvcmsiOmZhbHNlLCJlbnZpcm9ubWVudCI6Im9mZmxpbmUiLCJ1bnZldHRlZE1lcmNoYW50IjpmYWxzZSwiYnJhaW50cmVlQ2xpZW50SWQiOiJtYXN0ZXJjbGllbnQzIiwiYmlsbGluZ0FncmVlbWVudHNFbmFibGVkIjp0cnVlLCJtZXJjaGFudEFjY291bnRJZCI6ImM1eWN3MnN2eWtuendqdHoiLCJjdXJyZW5jeUlzb0NvZGUiOiJVU0QifSwiY29pbmJhc2VFbmFibGVkIjp0cnVlLCJjb2luYmFzZSI6eyJjbGllbnRJZCI6IjdlOTVlMGZkZGExNDg0NjY1OGIzOGY3NzJiYTJkMzBjZDc4YTlmMjE0NGM1MzkwODZlNTc5MGJmMzc3ZmJlZWQiLCJtZXJjaGFudEFjY291bnQiOiJjb2luYmFzZS1zYW5kYm94LXNoYXJlZC1tZXJjaGFudEBnZXRicmFpbnRyZWUuY29tIiwic2NvcGVzIjoiYXV0aG9yaXphdGlvbnM6YnJhaW50cmVlIHVzZXIiLCJyZWRpcmVjdFVybCI6Imh0dHBzOi8vYXNzZXRzLmJyYWludHJlZWdhdGV3YXkuY29tL2NvaW5iYXNlL29hdXRoL3JlZGlyZWN0LWxhbmRpbmcuaHRtbCIsImVudmlyb25tZW50IjoicHJvZHVjdGlvbiJ9LCJicmFpbnRyZWVfYXBpIjp7ImFjY2Vzc190b2tlbiI6InNhbmRib3hfNmRkdG13X3B6YjZ3cF93ZHdoY3lfOWhnNm5iX2N5NiIsInVybCI6Imh0dHBzOi8vcGF5bWVudHMuc2FuZGJveC5icmFpbnRyZWUtYXBpLmNvbSJ9LCJtZXJjaGFudElkIjoiaGg0Y3BjMzl6cTRyZ2pjZyIsInZlbm1vIjoib2ZmIn0'
      braintree.client.create({
        authorization: auth
      }, function (err, btClient) {
        braintree.paypalCheckout.create({
          client: btClient
        }, function (err, btPaypal) {
          paypal.Button.render({
           env: 'sandbox', // or 'production'

           locale: 'en_US',

           payment: function () {
             return btPaypal.createPayment({
               flow: 'vault'
             });
           },

           onAuthorize: function (data, actions) {
             return btPaypal.tokenizePayment(data).then(function (payload) {
               fillInForm(payload.details)
             }).catch(function (err) {
               // handle error
             });
           },

           onCancel: function (data) {
             console.log('checkout.js payment cancelled', JSON.stringify(data, 0, 2));
           },

           onError: function (err) {
             console.error('checkout.js error', err);
           }
          }, '#paypal-button'); // the PayPal button will be rendered in an html element with the id `paypal-button`
        })
      })

    function fillInForm (data) {
      document.getElementById('email').value = data.email
      document.getElementById('first-name').value = data.firstName
      document.getElementById('last-name').value = data.lastName
    }
    </script>
  </body>
</html>
```
