### ISSUE TITLE
Is it possible to redirect to Paypal or Gpay windown instead of opening a new tab?

### ISSUE THREAD

**Issue by vinhp1292** [braintree/braintree-web#581]
### General information

Braintree SDK version: 3.69.0
3.69.0

### Issue/discussion description

Hi team,
I'm the developer for an e-commerce site and I'm integrating payment gateways through Braintree SDK.
About the Paypal/Gpay, when making a payment it will pop up in a new tab. 
So Is it possible to redirect to the Paypal or GPay website instead of opening a new tab?

Very appreciate your support

**Comment by crookedneighbor** [comment]
No. The way both those SDKs work, they must open a new window to work. Though in the case of GPay, if you're on a native android device, it should open some native UI instead of opening a new window.

If you have additional questions about Google Pay's SDK, I'd recommend reaching out to Google directly.
