### ISSUE TITLE
Exception in 3D Secure handling in some cases (might be 3DSv1 handling related)

### ISSUE THREAD

**Issue by adig** [braintree/braintree-web#582]
###  General information

* SDK version: 3.79.1
* Environment: Production
* Browser and OS Edge 91.0.864 on Windows 10, Chrome 91.0.4472 on Mac OS X 10.14.6

### Issue description
We've had some clients complaining about not being able to go over the 3D Secure authentication step. We have identified the error described below as the cause in these cases. It seems to happen for clients with credit/debit cards that use 3DSv1. We weren't able to replicate the issue in a sandbox environment even when forcing the ThreeDSecure client to use 3DSv1. 

The problem is that `this._verifyCardPromisePlus` is null when `_handleV1AuthResponse` is called here: https://github.com/braintree/braintree-web/blob/main/src/three-d-secure/external/frameworks/base.js#L250 

This the stack trace, captured by our exception tracking platform: 

```
TypeError: Cannot read property 'resolve' of null
  at _handleV1AuthResponse(./node_modules/braintree-web/dist/browser/three-d-secure.js:2112:33)
  at _handleAuthResponseFromV1Fallback(./node_modules/braintree-web/dist/browser/three-d-secure.js:2760:8)
  at apply(./node_modules/braintree-web/dist/browser/three-d-secure.js:2770:12)
  at apply(./node_modules/braintree-web/dist/browser/three-d-secure.js:537:37)
  at dispatch(./node_modules/braintree-web/dist/browser/three-d-secure.js:734:51)
  at n.onmessage(./node_modules/braintree-web/dist/browser/three-d-secure.js:787:16)
```

**Comment by crookedneighbor** [comment]
Thanks for the report. Can you share your client side code? I assume you're setting the SDK up to use 3ds v2 and your customers' bank is going through the v1 flow instead.

**Comment by adig** [comment]
That's right, the setup is made with `version: 2`. Here's a simplified version of our setup / code, but please note that we weren't able to replicate the error with the sandbox env, and we haven't found a credit card that triggers the issue with the production environment.

```javascript
import BraintreeClient from 'braintree-web/client';
import BraintreeThreeDSecure from 'braintree-web/three-d-secure';

import { BRAINTREE_CC_ENDPOINT } from 'config';
import { generatePaymentMethodNonce } from 'api/payments';
import { checkEnrollStatus, addFrame, removeFrame } from 'utils/three-d-secure';

const updateCreditCard = (token, ccFormData, customerEmail, amount, planName) => {

	let braintreeClient;
	let threeDSecureInstance;

	BraintreeClient.create({authorization: token}, (error, client) => {

		if (error) {
			return console.error(error);
		}


		braintreeClient = client;

		BraintreeThreeDSecure.create({
			version: 2,
			client: braintreeClient
		})

		.then(threeDSecure => {
			
			threeDSecureInstance = threeDSecure;

			return braintreeClient.request({
				method: 'post',
				endpoint: BRAINTREE_CC_ENDPOINT,
				data: ccFormData
			});

		})

		.then(({creditCards}) => {

			let {
				nonce
			} = creditCards[0];

			// This is where the card is vaulted on the server side
			return generatePaymentMethodNonce({
				nonce: nonce,
				plan: planName
			});
		})

		.then(response => {

			let {
				nonce, 
				bin,
				authRegulationEnv
			} = response;

			return threeDSecureInstance.verifyCard({
				amount: amount,
				nonce: nonce,
				bin: bin,
				email: customerEmail,
				additionalInformation: {
					acsWindowSize: '03'
				},
				// We've added these only for testing with version: 1
				// I don't think these are called when using version: 2
				addFrame: addFrame,
				removeFrame: removeFrame
			});
		})

		.then(({threeDSecureInfo}) => {

			if(checkEnrollStatus(threeDSecureClient)) {
				console.log('success');
			} else {
				console.warn('failed 3dsecure verifyCard');
			}
		})
		
		.catch(error => {
			console.error(error);
		});
	});
};

```

Thank you!

**Comment by crookedneighbor** [comment]
Thanks for the info. We'll take a look.

**Comment by crookedneighbor** [comment]
Can you pass along your public merchant id? I have an inkling about what's going wrong and want to confirm.

**Comment by adig** [comment]
I believe this is our merchant id: `czwt3x4rnqxh9dtb` Let me know if I can help with other details.

**Comment by crookedneighbor** [comment]
We have analytics events fire for when the v1 fallback flow gets used. These typically only fire when the SDK for our 3DS provider (Cardinal) fails to set up correctly. Here are the analytics events we see for your integration for the last 7 days:

|kind | count|
| -- | --|
| web.three-d-secure.v1-fallback.cardinal-sdk-setup-failed.songbird-js-failed-to-load | 2 |
| web.three-d-secure.v1-fallback.cardinal-sdk-setup-timeout | 2 |
| web.three-d-secure.v1-fallback.cardinal-sdk-setup-error.number-10001 | 1 |
| web.three-d-secure.v1-fallback.cardinal-sdk-setup-error.number-0 | 2 |
| web.three-d-secure.v1-fallback.cardinal-sdk-setup-error.number-10004 | 64 |

For `songbird-js-failed-to-load`, we fire that here: https://github.com/braintree/braintree-web/blob/3da6d477feb0f02bec9fd5dad89de3fea4fd2d27/src/three-d-secure/external/frameworks/songbird.js#L365-L367

That typically occurs when the code that pulls in the Cardinal SDK fails. (maybe the CDN was unreachable, or the device lost internet connect while trying to pull down the script)

For `cardinal-sdk-setup-timeout`, we fire that here: https://github.com/braintree/braintree-web/blob/3da6d477feb0f02bec9fd5dad89de3fea4fd2d27/src/three-d-secure/external/frameworks/songbird.js#L358

And that should only fire if it takes longer than 60 seconds to initialize the Cardinal SDK.

The last batch of events, `cardinal-sdk-setup-error.number-*` fires here: https://github.com/braintree/braintree-web/blob/3da6d477feb0f02bec9fd5dad89de3fea4fd2d27/src/three-d-secure/external/frameworks/songbird.js#L464

And should only really happen if the callback that is supposed to be used to finish the 3DS Challenge gets called during the setup process. It's a weird quirk of the Cardinal SDK where this callback can be called in the case of a terminal error.

The documentation for the specific error codes are provided here: https://cardinaldocs.atlassian.net/wiki/spaces/CC/pages/100401153/Error+Codes

Though, since 0 is undocumented and the other 2 don't give us much to go on, it's hard to draw any conclusions here.

To my knowledge, it should be impossible to get to the point where it's calling `this._verifyCardPromisePlus.resolve` without having `this._verifyCardPromisePlus` set, but that's clearly not the case here.

I think our next step is to get specific timestamps in UTC so we can figure out exactly what failure flow is occurring, which should give us a better idea of how to diagnose why the state is incorrect.

**Comment by adig** [comment]
Thank you for the insights. I was able to gather the timestamps for three customers we've had where this error happened. For one of them we also captured an error message about cardinal, right before the exception happened, but we didn't capture any other information about the error, only the error message. Please find the timestamps below:

```
# Customer 1 - Edge 91.0.864, Windows
Jul 21, 2021 12:19:47 PM UTC -TypeError: Cannot read property 'resolve' of null
Jul 21, 2021 12:19:43 PM UTC -A general error has occurred with Cardinal. See description for more information.
Jul 20, 2021 4:45:18 PM UTC - TypeError: Cannot read property 'resolve' of null
Jul 20, 2021 4:44:28 PM UTC - TypeError: Cannot read property 'resolve' of null
Jul 20, 2021 1:03:33 PM UTC - TypeError: Cannot read property 'resolve' of null
Jul 19, 2021 1:02:13 PM UTC - TypeError: Cannot read property 'resolve' of null
Jul 19, 2021 1:01:53 PM UTC - TypeError: Cannot read property 'resolve' of null
Jul 15, 2021 8:31:38 AM UTC - TypeError: Cannot read property 'resolve' of null
Jul 15, 2021 8:31:15 AM UTC - TypeError: Cannot read property 'resolve' of null

# Customer 2 - Chrome 91.0.4472, MacOS
Jul 20, 2021 7:07:19 PM UTC - TypeError: Cannot read property 'resolve' of null

# Customer 3 - Chrome 91.0.4472, MacOS
Jul 18, 2021 10:17:15 PM UTC - TypeError: Cannot read property 'resolve' of null
```

**Comment by crookedneighbor** [comment]
We've just released a beta version that we _think_ will resolve the issue. (hard to tell, of course, since we can't replicate it) Can you upgrade your version to `3.79.2-beta.1` and let us know if you are still getting the `TypeError`?

**Comment by crookedneighbor** [comment]
We released the beta to npm as well, so should be as easy as updating the package.json

**Comment by adig** [comment]
Thank you! We have now updated the version in our builds, we're watching for any errors, I'll keep you posted. 
Have a nice weekend!

**Comment by crookedneighbor** [comment]
@adig any changes on your end?

**Comment by adig** [comment]
@crookedneighbor apologies for the delay. Everything looks good on our end, we haven't seen the error again.
If you feel comfortable with the changes, you can close this issue and apply them to the stable release. 

Thank you 🙏

**Comment by crookedneighbor** [comment]
Awesome, glad to hear it! We're hoping to get a release out this week.

**Comment by crookedneighbor** [comment]
This is out in v3.80.0
