### ISSUE TITLE
Set default payment method

### ISSUE THREAD

**Issue by arobert93** [braintree/braintree-web#585]
### General information

* SDK version: 3.79.1
* Environment: Sandbox
* Browser and OS : "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36"

### Issue description

Vault Manager is able to delete payment methods, but unable to set a payment nonce as default payment method. Would that be possible on client side? If not, what's the alternative?

**Comment by crookedneighbor** [comment]
It's not possible on the client. You can do the action on the server instead.

If you know the payment method token (not the nonce) for the payment method, you can use: https://developer.paypal.com/braintree/docs/reference/request/customer/update#default_payment_method_token

If you don't have the payment method token, you can create a new payment method using the nonce that represents the vaulted payment method and it'll give you the data for the already vaulted payment method. (rather than vaulting the same thing a second time)
