### ISSUE TITLE
Prevent vaulting until 3DSecure has been verified 

### ISSUE THREAD

**Issue by arobert93** [braintree/braintree-web#586]
### General information

* SDK version: 3.79.1
* Environment: Sandbox
* Browser and OS: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36"

### Issue description

Due to EU regulations, we need to check the 3DSecure before any payment or vaulting process. Currently, the hostedFields instance allows you to tokenize a credit card with vault true, without checking the 3DSecure, even with "Verify Card" set to "true" in the control panel settings (processing settings).

What we did to prevent the vaulting process until 3DSecure is complete was the following setup:

```js
 const payload = await hostedFieldsInstance.tokenize();

const verification = await threeDSecureInstance.verifyCard({
  onLookupComplete: function (data, next) {
    next();
  },
  amount: '0.00',
  nonce: payload.nonce,
  bin: payload.details.bin
});

const vaulted = await hostedFieldsInstance.tokenize({ vault: true });
```

Our setup is for a pay as you go strategy, where we do not make any upfront charges. We think that our implementation may not be correct, because a simple breakpoint allows you to intercept the function and add `"vault": true` in the first tokenization process.

**Comment by crookedneighbor** [comment]
If that is a requirement for you, you should instead vault only on the server side after you've verified the credit card has been verified by 3D Secure.

Since you're using 3D Secure, you'll most likely want to use the `store_in_vault_on_success` option when completing a transaction. See https://developer.paypal.com/braintree/docs/reference/request/transaction/sale#options.store_in_vault_on_success
