### ISSUE TITLE
ThreeDs lookup error handling

### ISSUE THREAD

**Issue by harris-jacob** [braintree/braintree-web#615]
### General information

* SDK version: 3.82.0
* Environment: sandbox
* Browser and OS Chrome: 98.0.4758.80 MacOS: 12.1

### Issue description
We recently had an issue on our frontend where three-d-secure verifyCard was returning a verify payload with a `lookup_error` status. As we were not checking this status field, the error was slipping through the cracks on our frontend and not informing anyone. 

In the [docs](https://braintree.github.io/braintree-web/current/module-braintree-web_three-d-secure.html), I notice that under the three-d-secure `on."lookup_complete")` handler, there is a comment that says `// check lookup data` however, the docs do not tell us how to do this or what potential scenarios to expect. As I said, in our case the issue was a `lookup_error` which was present in a `status` field, but this field does not exist in the docs' definition of a ThreeDSecureInfo object. 

### Ideal Outcomes
- either lookup errors or any other status errors cause the verify promise to reject
- or the the "status" field, its potential values and an example of how to check for them is added to the docs

**Comment by jplukarski** [comment]
Hello @harris-jacob, thanks for writing in; these are some great questions.

Our documentation is vague around the lookup data because that data is returned to us by our third-party MPI provider CardinalCommerce. Additionally, we cannot adjust the promise to reject in these cases because it is possible for a bank to accept the transaction even when these errors occur, [so we do not reject these transactions even if 3DS is required](https://developer.paypal.com/braintree/docs/guides/3d-secure/server-side#status-lookup_error-an-error-occurred-during-the-lookup-and-caused-3d).

I hope this has clarified things. I'm going to close this issue for now, but let us know if you have any additional questions.
