### ISSUE TITLE
Hosted Fields use inline styles in braintree-web@3.85.2 which violates our CSP

### ISSUE THREAD

**Issue by nstuyvesant** [braintree/braintree-web#625]
### General information

* SDK version: 3.85.2
* Environment: Production
* Browser and OS: Safari 15.4 on macOS 12.3.1

### Issue description

I use braintree-web@3.85.2 in my web app. A recent security audit found that we did no have a sufficiently restrictive Content Security Policy (CSP) so we tightened it.

Because Hosted Fields in braintree-web@3.85.2 use inline styles, we have to include 'style-src': 'unsafe-inline' which is not recommended.

Would it be possible for Hosted Fields to render using CSS classes from a stylesheet on https://*.braintreegateway.com/ so we do not have to enable 'unsafe-inline' styles?

**Comment by cgdibble** [comment]
Hey, @nstuyvesant , unfortunately no as that would prevent the Hosted Fields elements from being style-able via merchant configuration. 
That is, because we allow merchant's to style these elements via SDK configuration, we need to then apply those styles and thus a `<style>` tag is needed. We don't have a work-around for this currently.

**Comment by lol768** [comment]
This isn't a good reason - why can't you write a dynamic server-side endpoint (on braintreegateway.com) which returns back the merchant's CSS?

**Comment by maderlock** [comment]
Is there an update on this, given the imminent applicability of PCS DSS v4 at the end of the month?

**Comment by nstuyvesant** [comment]
We use TailwindCSS. I would rather pass a list of CSS class names.
