### ISSUE TITLE
Link PayPal account without clicking on btn (vault flow)

### ISSUE THREAD

**Issue by mkloar** [braintree/braintree-web#664]
### General information

- SDK version: [3.88.4](https://www.npmjs.com/package/braintree-web/v/3.88.4)
- Environment: Sandbox
- Browser and OS: All

### Issue description

Is it possible to open up the PayPal window without the user's action (aka. clicking on the PayPal button)? I want to link the customer's account (vault) to the Braintree so that I can later charge the user.

I have this code (which is working), but it is **deprecated**:
```js
import braintree from 'braintree-web';

const braintreeClient = await braintree.client.create({
  authorization: '...'
});

const paypal = await braintree.paypal.create({ client: braintreeClient });
// This will open up paypal window
const tokenizeData = await paypal.tokenize({ flow: 'vault'}); // DEPRECATED
const { nonce, details } = tokenizeData;
await linkMyAccount(nonce, details); // send to backend
```

Documentation is saying that this code is **deprecated**, so I want to use non deprecated code for vaulting.

One more question. Is it possible to set the width and height for the PayPal window (i.e full width and height)?

**Comment by cgdibble** [comment]
The PayPal window/popup needs to be the result of a user action because of how browsers handle popups. Browsers require that user action because popups have been so frequently abused over the years. This means we, as browser users, aren't having any old script loaded on a page shove a popup in our face (thankfully!).

It certainly does provide some complications in this context, though!

This previous PayPal integration is indeed deprecated. But, that is because we have instead a more direct integration with the PayPal SDK: https://developer.paypal.com/braintree/docs/guides/paypal/client-side

But, more explicitly...
> Is it possible to open up the PayPal window without the user's action
No, because browsers will block it, regardless of it being this deprecated version or the more recent one. 

> so I want to use non deprecated code for vaulting.
Check out our docs on the [latest PayPal integration](https://developer.paypal.com/braintree/docs/guides/paypal/client-side) to avoid issues around the deprecated one you are using.

>  Is it possible to set the width and height for the PayPal window
With the way we integrate PayPal now, that is ultimately up to what the PayPal SDK supports.
