### ISSUE TITLE
Hosted fields triggers cardTypeChange multiple times when when it's autofilled by browser

### ISSUE THREAD

**Issue by ruslantimofeev** [braintree/braintree-web#695]
### General information

- SDK version: 3.97.1
- Environment: sandbox
- Browser and OS Chrome 115.0.5790.170 (64-bit) on MacOS 13.4.1

### Issue description

When autofilling the form with saved card in Chrome the SDK triggers **cardTypeChange** event 4 times that does not seem correct as the type changes only once.

![on-card-type-chage](https://github.com/braintree/braintree-web/assets/142988915/8b212d37-a6f4-4133-a30d-08a800aa837e)

Example https://codepen.io/rustavely/pen/LYMxavd

**Comment by jplukarski** [comment]
@ruslantimofeev  thanks for bringing this to our attention. We'll add a ticket to our backlog to look into fixing this bug.

For internal tracking purposed -> 22016

**Comment by jplukarski** [comment]
@ruslantimofeev After some investigation, this is occurring because of the way Chrome mimics user input in its autofill feature (this issue does not happen on Firefox). Moreover, there is no way to detect if chrome autofill has been used to fill in data via javascript. We're going to close this issue since we cannot control how Chrome fills in the data via autofill.

Let us know if you have any other questions.
