### ISSUE TITLE
No callback function for loadPayPalSDK method

### ISSUE THREAD

**Issue by ruaridhnewman** [braintree/braintree-web#703]
### General information

- SDK version: 3.97.2 
- Environment: Any 
- Browser and OS: Any 

### Issue description

I'm trying to use the `loadPayPalSDK` method instead of using the paypal.com script directly, but am having issues with success/error handling on attempting to call it. In the docs, it says you can pass a callback method to the `loadPayPalSDK` function (see [here](https://braintree.github.io/braintree-web/current/PayPalCheckout.html#loadPayPalSDK) and [here](https://developer.paypal.com/braintree/docs/guides/paypal/checkout-with-paypal/javascript/v3/)), but that never appears to be triggered, and I can see in the `braintree-web` code that it doesn't accept a callback as far as I can tell:

[paypal-checkout.js, L1186](https://github.com/braintree/braintree-web/blob/1671fc6c4189476e883bc4a9ab7639238236aecc/src/paypal-checkout/paypal-checkout.js#L1186-L1187)

```js
PayPalCheckout.prototype.loadPayPalSDK = function (options) {
  // code
}
```

This means that I can't update my checkout page on an unsuccessful attempt at loading the paypal SDK, which has caused me some issues with users attempting to buy something from the site I work on.

Here's a minimal repliacation:

[CodeSandbox](https://codesandbox.io/p/sandbox/elegant-pine-f7n8c4?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpgvd7jk00083b6if4q1aok7%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpgvd7jk00043b6il6q8han5%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpgvd7jk00053b6ir6j9zk2g%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpgvd7jk00073b6i4uk3s41k%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpgvd7jk00043b6il6q8han5%2522%253A%257B%2522id%2522%253A%2522clpgvd7jk00043b6il6q8han5%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clpgvd7jk00073b6i4uk3s41k%2522%253A%257B%2522id%2522%253A%2522clpgvd7jk00073b6i4uk3s41k%2522%252C%2522activeTabId%2522%253A%2522clpgxh82c039j3b6iquk50eg8%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clpgxh82c039j3b6iquk50eg8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%255D%257D%252C%2522clpgvd7jk00053b6ir6j9zk2g%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpgvd7jk00053b6ir6j9zk2g%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Note: you will need to generate a client token and add it to the `CLIENT_TOKEN` variable in `BraintreePayment.js`.

Essentially what happens in this flow is it gets to the call to use `loadPayPalSDK`, but on failing to load the script it never calls the callback method that gets passed into it:

```js
this.#payPalInstance.loadPayPalSDK(options, callback)
```

=> `callback` is never called, so I can never know for sure if it errored.

**Comment by simeyla** [comment]
I had a strange, yet similar issue with manual loading of the PayPal script today. 
I load it by dynamically adding a script tag and setting it to `'https://www.paypal.com/sdk/js?client-id=....&...`. In fact I hadn't even seen this `loadPayPalSDK` option before.

Was noticing that on my iPhone (currently iOS 17.2) it wasn't running the callback for `onload` (so my Express Checkout button failed), but in Chrome on my Windows machine it was. I could load the script by pasting the URL into Safari just fine - it loaded instantly.

I actually had started to wonder if iOS was getting clever and stripping out the `client-id` parameter if it was thinking it was a [tracking parameter](https://www.apple.com/newsroom/2023/06/apple-announces-powerful-new-privacy-and-security-features/). 

But I just got back from an airport run and it's all working again normally without touching anything. So I'm still puzzled, but wanted to mention what I'd seen since it sounded so similar. When you said 'Any browser' did you really mean any browser?

**Comment by ruaridhnewman** [comment]
> When you said 'Any browser' did you really mean any browser?

I've tried on Firefox, Chrome, Safari on my mac, and it never triggers the callback on failing to load the script. Haven't tried on mobile, but I'm assuming it's the same considering it's all the browsers on desktop 🤷

**Comment by jplukarski** [comment]
Hello @ruaridhnewman , thanks for this report.

> I can see in the braintree-web code that it doesn't accept a callback as far as I can tell:

We have built a module [wrap-promise](https://github.com/braintree/wrap-promise/tree/main) to bring callback functionality to the SDK. [Here is where it is implemented in the PayPalCheckout component.](https://github.com/braintree/braintree-web/blob/main/src/paypal-checkout/index.js#L65).

I am able to successfully get the callback function to execute in my own simple integration. Taking a look at your code, it looks like you are using a combination of both callbacks and promises:

```
 loadPayPal = async ({ onSuccess, onError }) => {
    return this.#payPalInstance.loadPayPalSDK(
      {
        'client-id': 'invalid-client-id',
        components: 'buttons,messages',
        currency: 'GBP',
        'enable-funding': 'paylater',
        dataAttributes: {
            amount: 12.34
        }
      },
      // THIS IS NEVER CALLED
      (error) => {
        if(error) {
          onError(error.message)
          throw new Error('Something went wrong loading PayPal SDK')
        }
        
        onSuccess();
      }
    )
  }
```

I would suggest either using promises or callbacks. Moreover, since it looks like this is an issue with your integration and not a bug in the SDK, I can suggest [reaching out to our Support Team](https://developer.paypal.com/braintree/help) who can help you with issues in your own integration.

@simeyla , it sounds like your issue is unrelated. I can also suggest reaching out to our support team if you continue to experience the `onload` callback not executing.
