### ISSUE TITLE
Drop-in flips to "vaulted" appearance upon order form submission

### ISSUE THREAD

**Issue by RikdeBoer** [braintree/braintree-web#72]
Using any of the recent versions of the .js, including the current "official" one from https://js.braintreegateway.com/v2/braintree.js we're seeing some undesirable behaviour.

It starts off ok.
When the (single) checkout page containing the `braintree.setup()` is called with a clientToken generated on the server *without* a `customerId` passed in, the drop-in form appears as it should: with PayPal button and fields for credit card number, expiry and CVV (CID for Amex).
```javascript
   var dropInOptions = {
        container: 'dropin-braintree',
        onPaymentMethodReceived: insertNonceOnForm
    };
    var clientToken = '<?php echo $_clientToken; ?>';
    braintree.setup(clientToken, 'dropin', dropInOptions);
```

<img width="234" alt="drop-in before submit" src="https://cloud.githubusercontent.com/assets/4031225/9974204/6b41b83c-5ec8-11e5-93a8-b4e72ba94041.png">

When the shopper presses "Place Order" on the checkout form, we capture and park the click, then programmatically press the hidden button on the drop-in form to have the nonce generated on our checkout form.
We then re-instate the handler on the "Place Order" button to let it do its thing, which is to submit everything on the checkout form (product and shipping details, nonce) to the store.
All of this has worked beautifully with a version of the .js dating back to May (we think).
It still works with later versions (we tried 2.7.4 and 2.14.0) in that the order gets processed. 
But there is a major difference: when the checkout form submit occurs, the drop-in changes its look to the "vaulted" appearance, showing the last two digits of the credited card and a "Change payment method" link.

<img width="234" alt="drop-in after submit" src="https://cloud.githubusercontent.com/assets/4031225/9974209/8faa11ec-5ec8-11e5-8c81-b41f060c5fe0.png">

This isn't so bad when the order goes through, as the shopper will be redirected to some sort of success page. End of story.
But it is a major UX issue when the sale is declined and the shopper is left on the page with the drop-in having changed its looks and the original input fields no longer available.

To correct card details, say a CVV/CID, the shopper then needs to either refresh the page (losing all data entered) or using the drop-in vault look add a payment method (which is counter intuitive) and retype *all* of their card details, as these are not pre-populated. They can then press "Place Order" order a second time (since v2.7.4 will now auto-generate a NEW nonce, yay!) and the order will go through.

Is this behaviour configurable at all? 

We much prefer the old behaviour whereby the drop-in retains its original look & feel, however we cannot use versions prior to 2.7.4 because of https://github.com/braintree/braintree-web/issues/20
Versions prior to 2.7.4 return the previously generated nonce, which then gets rejected on the server in the `sale()` call, for being used twice.

Note that in all this the Vault is off in that no `customerId` is ever past to the `Braintree_ClientToken::generate` or `Braintree_Transaction::sale()` calls.

**Comment by EvanHahn** [comment]
@RikdeBoer I'll take a look at this. Thanks for reporting!

**Comment by RikdeBoer** [comment]
@EvanHahn,

That would be fantastic. To us and our customers it is a serious UX issue. The use-case is very common: a one-page checkout page, where the drop-in is not the only element on the page, and the order is placed through an AJAX call. 

Like this one:
![image](https://cloud.githubusercontent.com/assets/4031225/10061628/ddfb4644-629d-11e5-88f0-4ca4a47e9858.png)

In this scenario, if there is an error in the backend, the shopper is not redirected to another page, but stays on the same page. 

This then raises two issues:

o we need the drop-in to generate a NEW nonce (not the same one) -- this was supposedly fixed with 2.7.4 but it is not (please see my comments to this issue https://github.com/braintree/braintree-web/issues/20, which I feel should be re-opened)

o we need a convenient way, *other* than a page refresh or *"Change payment option"* for the shopper to correct their CVV or expiry

**Comment by EvanHahn** [comment]
Unfortunately, Drop-in doesn't work in every use case. We've tried our best to make it work in all cases, but we can't anticipate all of them.

Luckily, we've made [Hosted Fields](https://www.braintreepayments.com/features/hosted-fields), which offers much more customization. That should help address this issue! If you experience any problems, please don't hesitate to email <support@braintreepayments.com> or add another issue.

**Comment by RikdeBoer** [comment]
Hi Evan & team,

This is not a special case. It is the most popular case of all: a checkout page with the drop-in on it! Millions of shoppers all over the world use it this way.

And it used to behave exactly as it should: which is to simply leave the drop-in form as is. At some point this was changed to flip to the "Change payment method" look and now millions of shoppers cannot correct their credit card details when the gateway says there's a typo (or other error) in their card details.

We are in touch with dozens of merchants who are turning their backs on Braintree and the the drop-in because of the impossible UX that results when shoppers make a typo in their credit card details. See screenshot above.

I cannot see any use-case for the current behaviour, but if you must have it, that's fine by me.
But please let us pass in a flag in the setup options to activate to the old, and much simpler, behaviour.

Pointing us to Hosted Fields is not an acceptable response -- why do Braintree offer the drop-in, if you feel Hosted Fields should be used instead?

**Comment by EvanHahn** [comment]
Apologies for the confusion. I should have elaborated more in my previous reply. Let me try to explain here.

Of course Drop-in is designed to support the general use case of a payment form on a checkout page. However, Drop-in does not currently support a kind of "edit" flow where a customer goes back and edits their payment information. We can't support this because we have to maintain backwards compatibility for all of our merchants.

Since you've brought it up, we've discussed this a ​_lot_​ internally and we have definitely taken your feedback to heart. Future versions of `braintree.js` will likely address these concerns, but because of backwards compatibility constraints (and others), we can't fix this.

You can completely reset Drop-in to its original state by tearing it down and starting it up. This isn't exactly what you want, but it might be a bit better than doing a full page refresh. Here's a bit of sample code to get you started:

```js
var braintreeIntegration;

var clientToken = '<?php echo $_clientToken; ?>';

function setupBraintree() {
  var dropInOptions = {
    container: 'dropin-braintree',
    onPaymentMethodReceived: insertNonceOnForm,
    onReady: function (integration) {
      braintreeIntegration = integration;
    }
  };

  braintree.setup(clientToken, 'dropin', dropInOptions);
}

// When you have a server-side error with credit card details,
// you can COMPLETELY reset dropin:
myCheckoutForm.onInvalidCreditCardDetails = function () {
  if (braintreeIntegration) {
    braintreeIntegration.teardown(function () {
      braintreeIntegration = null;
      setupBraintree();
    });
  }
};
```

**Comment by RikdeBoer** [comment]
Ok, I won't push any further.

Just this...

If you are talking about *backwards compatibility* ... This never used to be the default behaviour.  It is a regression. The default behaviour, months ago, used to be exactly what we all want: to leave the card number, expiry and CVV fields exactly as they were left by the shopper. No erasing. No flipping to a little panel that says “VISA ending in 11”. Just do *NOTHING*.

Then if there is a gateway error, those fields are still there for the shopper to correct. Then they press “Place order” for a second time, NEW nonce gets generated, order goes through. Happy days.

Does that make sense? Would you agree that this is a better UX than the current behaviour? Do you agree that teardown() is not going to do much for the shoppers and merchants in this scenario?

Final question: when shoppers complain to the merchants that we do business with, do I quote this as the official Braintree response:

*"Future versions of braintree.js will likely address these concerns."* 
*"Until such time (release date unknown), refresh the page or re-initialise the drop-in, thereby losing all data entered."*

**Comment by burnto** [comment]
Have you considered trying this with a customer ID in the client token? That's the intended way of using drop-in, and any card verification rules will be applied in tokenization and, if verified successfully, the card will be saved to the customer.

**Comment by RikdeBoer** [comment]
Thanks for the suggestion burnto. 
But that scenario won't work, I don't think, for first time visitors or in fact any visitor who hasn't had their customerId generated and stored in the Vault. Some of our clients (merchants) do not like the Vault and therefore we made it an option for merchants to switch it off in our Magento extension.

**Comment by burnto** [comment]
I think you're encountering unspecified behavior here with tokenizing a card via drop-in without a customer ID. We'll take a closer look at the gateway code on Monday to investigate this hunch. 

Regarding your observation that this used to work as expected but no longer does, it's likely that the drop-in UI behavior was updated in the past without taking into account your use case, because it wasn't an expected or typical one. With a customer ID, the verification happens at tokenization in drop-in, rather than at transaction time in your scenario. So if verification passes, it is ok to show the vaulted state. Make sense?

We'll have a firmer explanation and a recommended action next week. Thanks again for this feedback.

**Comment by RikdeBoer** [comment]
Hi @burnto,
Very much appreciate you re-opening this issue. Look forward to the "firm explanation".

Yes the issue hurts most to shoppers who do not have their payment method stored in the Vault, e.g. those that arrive for the first time or those using an online store that has been configured to never pass a customerID, of which we have seen a few. In these cases the shopper enters card, expiry and CVV.

But even for a correctly Vaulted payment method there is a UX problem due to #20 not being fixed 100% I feel the drop-in must generate a NEW nonce on EVERY new form submission. This was supposedly fixed with 2.7.4 and the issue closed, but I found no new nonce is generated when the same payment method is used. Hence when the vaulted credit card is correct, but payment fails because of a different reason ("Temporarily unavailable", "Insufficient funds") we have a similar UX foible: pressing "Place order" a second time results in rejection with "Cannot use same nonce a second time". 

Shopper can only get out of this situation through a full page refresh (losing all other data on the page, like shipping details, coupon code, gift wrap options). Or since a couple, by the developer using the new function, teardown(), which is a little crude, when all we need is new nonce.

See my comments at the bottom of issue #20.

**Comment by burnto** [comment]
@RikdeBoer thanks. We discussed this internally at length.

If one provides a customer ID when generating the client token, then the Drop-in UI vaults the card as a payment method for that customer. And if verification rules are enabled in the Braintree control panel, then Braintree will only vault a card if it is valid according to those rules. If the card is not valid, the Drop-in UI will display an error accordingly.

The Drop-in UI does not support card verification _without_ a customer ID in the client token. So when no customer ID is provided, the card will still be tokenized (resulting in a nonce), but that nonce may or may not be a valid card, and a later `transaction.sale` on your server may fail accordingly.

From what I understand of your use case, you wish to be able to tokenize in this manner, without a customer ID, then perform card verification via a subsequent `transaction.sale` (or similar server operation), and then allow the customer to edit their input.

It sounds like you were previously able to allow the customer to edit their input in the card form by taking advantage of a deficiency in the Drop-in behavior, in which presence of `onPaymentMethodReceived` prevented the UI from advancing to the "vaulted" view. Note that, in this deficient version, even after the form might be edited, the original nonce was maintained, which was absolutely incorrect behavior. This deficiency was subsequently resolved in 2.7.4 in order to support the intended use case of [tokenizing multiple payment methods](https://github.com/braintree/braintree-web/issues/20), and the UI now properly advances to the vaulted view after tokenization. We do not intend to re-enable the previous deficient behavior.

Our recommendation is that you either limit your use of Drop-in to scenarios in which you have a customer ID so that you can verify the card up front and allow user editing, or that you recommend Hosted Fields to your customers seeking this kind of guest checkout functionality. Hosted Fields has recently left beta and is a stable product offering.

**Comment by RikdeBoer** [comment]
Ok, I lose.

Re: *"And if verification rules are enabled in the Braintree control panel, then Braintree will only vault a card if it is valid according to those rules. If the card is not valid, the Drop-in UI will display an error accordingly."*

It's not "guest checkout" functionality. It's "first-time customer checkout" functionality. Or lack thereof.

We don't have a customer ID until the shopper has made a successful purchase.

Expiration date and CVV aren't checked by the drop-in are they? So those errors will still require a round-trip to the gateway, right? And then the shopper cannot enter correct expiry and/or CVV, other then by adding a new payment method , because of the "vaulted" form appearance.

Fine.

We will tell our merchants to use Hosted Fields if they want decent UX when shoppers make typos or the gateway rejecting the transaction for some reason other than a typo.

Will also have to tell them that by going for Hosted Fields they'll miss out on the goodies from the drop-in, like automatic card number spacing.

**Comment by burnto** [comment]
If you're implementing a first time checkout followed by sign up, it's actually pretty typical to generate a BT customer ID up front, rather than waiting until after the transaction. Perhaps this is an approach you'd want to consider.

**Comment by RikdeBoer** [comment]
Will certainly go through that scenario as well @burnto. Thanks again to you and your colleagues for having dug deep on this one and offering solutions and workarounds. I understand there is much more to this issue than what the superficial merchant & shopper eyes see. I'm certainly aware that presenting a top notch UX in the face of PCI compliance is a complex beast and a tough nut to crack.
Keep up the great great work on the drop-in and the Hosted Fields. Both far outstrip any competition. And your docs and prompt support are just awesome. Congrats to you all!

**Comment by chrisribe** [comment]
Hi,

Is this still the ONLY default behavior for the dropin form?

I am having the exact same issue. My users can enter invalid cvv or expiration dates, I get the error from braintree but the "vaulted" view is shown to the user. So he cannot correct / fix his mistake(s) and has the only options of either choosing another payment option OR reloading the payment page.

As @RikdeBoer said great form but lacks this basic functionality. It's the type of friction in a payment process that is highly undesirable!

Christian

**Comment by crookedneighbor** [comment]
@chrisribe I recommend updating to the [latest version of Drop-in (1.7.0)](https://github.com/braintree/braintree-web-drop-in).

It has a [clearSelectedPaymentMethod](https://braintree.github.io/braintree-web-drop-in/docs/current/Dropin.html#clearSelectedPaymentMethod) function that allows you to remove the selected payment method. For your use case, you'd tokenize with drop-in, send the payment method nonce to your server, get the validation error and then call `clearSelectedPaymentMethod` and add an error message to your page about it.
