### ISSUE TITLE
Error using latest braintree-data.js in a single page app

### ISSUE THREAD

**Issue by pkenway** [braintree/braintree-web#80]
We have a braintree integration currently using braintree-data-0.1.6 (at least that's what the JS file is called in our repo. I don't see any version numbers for the library anywhere)  I tried out the latest version of braintree-data and I'm having the following issue:

The first time I create the form it works, but on the second instance BraintreeData bails on the setup call.
```BraintreeData.setup(braintree_merchant_id, this.bt_form_id, env)```

throws this:
```Uncaught TypeError: Cannot read property 'getElementsByTagName' of null (braintree-data.js:100)```

The error comes from this line in braintree-data.js:

```
params="?m="+this.currentEnvironment.getId()+"&s="+this._getDeviceSessionId();iframe=document.createElement("iframe");iframe.width=1;iframe.id=BraintreeData.iframeId;iframe.height=1;iframe.frameBorder=0;iframe.scrolling="no";document.body.appendChild(iframe);setTimeout(function(){iframe.src=self.currentEnvironment.url+"/logo.htm"+params;iframe.innerHTML="<img src=\""+self.currentEnvironment.url+"/logo.gif"+params+"\" />";},10);};BraintreeData._formHasInput=function(form,input_id){var children=form.getElementsByTagName("input");var hasInput=false;for(var i=0;i<children.length;i+=1){if(children[i].id==input_id){hasInput=true;break;}}
```

The old version of our code was using the setupCollector function which now seems to be internal.  Is there something I should be doing differently or is this a bug? I'm thinking maybe the `setup` function should only be called once over the life of the app?

**Comment by lilaconlee** [comment]
@pkenway We've added a formless version of braintree-data to our roadmap that should help with this issue. We'll keep you updated on our progress here and on related issue #27.

**Comment by osener** [comment]
Version [2.16.0](https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md#2160) seems to include `braintree-data`. Is there a way to use this functionality with custom integration?

**Comment by kyledetella** [comment]
@pkenway we just released a new way to implement `braintree-data` in your integration that will alleviate the problem you are seeing. As of [`2.16.0`](https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md#2160) (as @osener mentioned) this new functionality was bundled into `braintree.js`. The latest release is currently [`2.17.2`](https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md#2172).

We just bumped our hotlink from `2.15.4` to `2.17.2` so the official documentation will be available on our [docs site](https://developers.braintreepayments.com/) within the next day or so. I will update here when that is available.

**Comment by florrain** [comment]
The [online doc for the fraud check tools](https://developers.braintreepayments.com/guides/advanced-fraud-tools/client-side/javascript/v2) doesn't mention the free fraud check `braintree-data.js` anymore but only kount.

Is that because it's no longer supported or because the doc hasn't been updated?

Tagging @kyledetella you'll most likely have the answer to that question. Thanks!

**Comment by kyledetella** [comment]
@florrain under the hood, the mechanics of the [Advanced Fraud Tools](https://developers.braintreepayments.com/guides/advanced-fraud-tools/client-side/javascript/v2) are the same as they were in `braintree-data.js`.

With the recent change, however, these fraud tools are now bundled with the `braintree.js` library and provide a more cohesive interface for usage with Braintree integrations. The `kount` and `paypal` options are now offered for use individually or together. In the previous iteration, both would be instantiated regardless of your integration type. It is also important to note another significant change in this new integration pattern which is the fact that it is up to you to provide the `device_data` value to your server since it is no longer silently injected as a hidden field into your `form`. See [this comment](https://github.com/braintree/braintree-web/issues/118#issuecomment-167845252) for more information.
