### ISSUE TITLE
Drop-in UI and billing address

### ISSUE THREAD

**Issue by fireflystorm** [braintree/braintree-web#93]
I have a form with drop-in UI and a few text boxes for billing address.
What is the correct way to set or update address for a payment method selected with Drop-in UI?

I notice that if the user added a new payment method in Drop-in UI and submits it I am able to use PaymentMethod.Create() passing the payment_method_nonce and billing request and that will set the billing address.

However if the user didn't add a new payment method then PaymentMethod.Create() returns success but doesnt update the payment method's billing address.

How can I update the billing address for a payment method when all I have is payment_method_nonce so I don't know if a new payment method has been added or an existing one is to be updated(and which existing payment method)?

**Comment by ryanjpodonnell** [comment]
@fireflystorm When you create a [Transaction#sale](https://developers.braintreepayments.com/reference/request/transaction/sale), you can pass an option [add billing address to a payment method](https://developers.braintreepayments.com/reference/request/transaction/sale#options.add_billing_address_to_payment_method) as well as an option to [store a payment method](https://developers.braintreepayments.com/reference/request/transaction/sale#options.store_in_vault).

However, this will not overwrite an existing billing address. In order to do this, you must use a [PaymentMethod#update](https://developers.braintreepayments.com/reference/request/payment-method/update) call.

I’m going to close this issue as I believe this answers your questions, but please reach out to our support team with future questions or concerns (support@braintreepayments.com).
