### ISSUE TITLE
Hosted fields do not work on <input> elements.

### ISSUE THREAD

**Issue by parreirat** [braintree/braintree-web#94]
When targeting the hosted fields at input elements, the lib does not throw an error, nor do anything.
Spent a couple of hours until we figured this out, when we saw an example page showing how to use the Hosted Fields (which we later noticed were div elements).

Is this intended? It should throw an error when selectors target input elements, if it doesn't work with those. I think that's the most logical thing to use as elements for a form.

And the Braintree JS documentation should definitively mention this, at least the troubleshooting FAQ bit.

Thanks.

**Comment by kyledetella** [comment]
@parreirat thanks for bringing this up. Regarding the decision to use `div`s as containers instead of `input` elements; that is indeed intentional. In a typical form, `input` elements are semantic, however we are providing synthetic input elements via individual iframes with Hosted Fields. By requiring `div` elements as injection targets, it allows us to present these iframes with limited side-effects to the parent form and its DOM tree. 

Having said that...I just re-read our documentation and you are correct, we do not make that explicit enough. We will update those docs soon and clear that part up. I will also talk with the team about providing error messaging when targeting `input`s instead of `div`s.

In the meantime, take a look at [this blog post](https://www.braintreepayments.com/blog/your-checkout-our-iframes) for a bit more insight into some design decisions around Hosted Fields.

Let us know if you have any more issues with your integration.

**Comment by parreirat** [comment]
For the record, I did not mean to show any opposition to the decision of injecting the iframes on the div element.

Sounds great to have the documentation/errors thrown when someone might do the same as we did by targeting input elements.

Thank you. :)

**Comment by kyledetella** [comment]
@parreirat my apologies if my response came off overly defensive. We will be improving the documentation on this matter. Again, I appreciate the feedback!

**Comment by parreirat** [comment]
Don't worry, it didn't, I thought that my ticket, on the other hand, could've sound a bit offensive (and to be honest, at the time I was pretty pissed off that I'd spent an afternoon around something like that).

Thanks and good work. :+1:

**Comment by corinabiro** [comment]
What if I want to use this hosted fields on a page only for mobile and want to use HTML 5 inputs, especially for expiration Date ?
 <input type="month" name="month" id="cardExpDate"> 
so that when the user taps on the input a dialog opens to choose the date instead on writing it?
also for the card number to set type="number" so that the keyboard is only with numbers.

How can I resolve this?

**Comment by parreirat** [comment]
Don't take my answer for an absolute truth, but I believe you can't do that due to how iFrames work.

**Comment by corinabiro** [comment]
Yes :( I was thinking about that, but hoping there is a solution.

**Comment by parreirat** [comment]
Allowing HTML5 date inputs to be used with Hosted Fields would likely require alot of work on their side...

**Comment by EvanHahn** [comment]
In short, you can't use HTML5 date inputs in Hosted Fields.

@parreirat is right. PCI compliance and iframes both work against us here. We mostly have to stick with what we have.

Speaking to input types: the expiration date is set to `tel` which makes many mobile devices use a number-only keyboard. (Setting it to `number` doesn't quite do what we want, unfortunately.) You can split the expiration date into `expirationMonth` and `expirationYear` if you'd like.

**Comment by lilaconlee** [comment]
@parreirat Just wanted to let you know that we added some documentation about using `<div>` as opposed to `<input>` in our [Hosted Fields FAQs](https://developers.braintreepayments.com/guides/hosted-fields/faq). Thanks for the suggestion!

**Comment by parreirat** [comment]
That's great to hear, I'll take a look.

Thank you, keep up the good work! :)

On Wed, Dec 2, 2015 at 3:36 PM, Lila Conlee <notifications@github.com>
wrote:

> @parreirat <https://github.com/parreirat> Just wanted to let you know
> that we added some documentation about using <div> as opposed to <input>
> in our Hosted Fields FAQs
> <https://developers.braintreepayments.com/guides/hosted-fields/faq>.
> Thanks for the suggestion!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/braintree/braintree-web/issues/94#issuecomment-161336464>
> .
>



-- 
Tiago Parreira
Junior Developer | *Passworks*
+351 967 637 997 <00351967637997>, @parreirat
passworks.io, @passworksio <https://twitter.com/passworksio>
